### ISSUE TITLE
Using OpenAI API key from client-side settings dialog generating code... ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by amaralkaff** [abi/screenshot-to-code#100]
Using OpenAI API key from client-side settings dialog
generating code...
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/starlette/middleware/cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/Users/amangly/Hacktiv8/Phase-3/1w/1d/screenshot-code/screenshot-to-code/backend/main.py", line 121, in stream_code
    completion = await stream_openai_response(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amangly/Hacktiv8/Phase-3/1w/1d/screenshot-code/screenshot-to-code/backend/llm.py", line 23, in stream_openai_response
    completion = await client.chat.completions.create(**params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 1191, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1474, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1275, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/amangly/Library/Caches/pypoetry/virtualenvs/backend-buPSjRcr-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1318, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
INFO:     connection closed

**Comment by siYuanJun** [comment]
openai.InternalServerError: Error code: 500 - {'code': -1, 'msg': '服务器错误', 'sn': '1bb3c14fe10604540e3cacedbdad3d07'}

**Comment by abi** [comment]
Hi there, please open a new issue. What you're encountering is likely just a temporary OpenAI failure. If you try again, it should work.
