### ISSUE TITLE
Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue.

### ISSUE THREAD

**Issue by sandeep2048** [abi/screenshot-to-code#126]
Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue.
i am getting this error while running the code from docker

**Comment by ramseyjiang** [comment]
The same issue, I didn't use docker, and I cannot find the backend logs in the backend directory. Don't know why

**Comment by ramseyjiang** [comment]
poetry run uvicorn main:app --reload --port 7001                                
INFO:     Will watch for changes in these directories: ['/Users/daweijiang/Desktop/screenshot-to-code/backend']
INFO:     Uvicorn running on http://127.0.0.1:7001 (Press CTRL+C to quit)
INFO:     Started reloader process [32625] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/daweijiang/Library/Caches/pypoetry/virtualenvs/backend-PZ3Tvq_3-py3.11/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/daweijiang/Library/Caches/pypoetry/virtualenvs/backend-PZ3Tvq_3-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/daweijiang/Library/Caches/pypoetry/virtualenvs/backend-PZ3Tvq_3-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/Users/daweijiang/Library/Caches/pypoetry/virtualenvs/backend-PZ3Tvq_3-py3.11/lib/python3.11/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daweijiang/Library/Caches/pypoetry/virtualenvs/backend-PZ3Tvq_3-py3.11/lib/python3.11/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/Users/daweijiang/Library/Caches/pypoetry/virtualenvs/backend-PZ3Tvq_3-py3.11/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/daweijiang/Desktop/screenshot-to-code/backend/main.py", line 2, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

Hope these above can help you to know the reason

**Comment by abi** [comment]
Did you do poetry install and then, poetry shell? Looks like you don't have the dotenv module installed.

**Comment by Jadenyoky** [comment]
I'm try the website and build it on docker ,, and i',m still stuck in this proplem ...

**Comment by ramseyjiang** [comment]
<img width="1263" alt="Screenshot 2023-11-30 at 13 17 58" src="https://github.com/abi/screenshot-to-code/assets/6574141/cb0e085a-daeb-46f5-91a5-d515f3a9aa17">

**Comment by ramseyjiang** [comment]
The above screenshot is after I did pip3 poetry install and poetry shell, met the same issue

**Comment by sandeep2048** [comment]
@abi i am using this website https://screenshottocode.com/ even thought i am getting the same error {"Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue."}  .do you think is there something wrong with my API key

**Comment by ConnorCHN** [comment]
a same problem
![Uploading image.png…]()

**Comment by ConnorCHN** [comment]
I've updated to the latest version, re-deployed it, and thought the problem was not configuring the base_url. But after setting the base_url, it still shows the error "Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue." It seems the problem is not with the base_url. I'm not sure where the problem lies.

**Comment by Avengoner** [comment]
Change 7000 to 7001

**Comment by mritunjayagarwal** [comment]
The issue is still there. I am not using docker. Is it alright? I am also not having any logs in the console. Just having these two annoying notifications even after providing correct Open AI Key

**Comment by abi** [comment]
@mritunjayagarwal what are you seeing in your backend logs?

**Comment by mritunjayagarwal** [comment]
no log is being displayed

**Comment by abi** [comment]
Can you screenshot whatever logs you see and send it over?

**Comment by ereilly220** [comment]
I was having this issue as well, what you have to do is change the url in the .env in your frontend folder to match the uvicorn url you get when starting the server. Likely the same issue I had with .env having port 7001 but server running on 7000.

**Comment by abi** [comment]
We had the unfortunate mistake of updating this repo to use 7001 when it started out using 7000. Did you pull the repo early and have since updated?

**Comment by Hellen20030926** [comment]
Having the same issue, here are my docker logs
![Uploading image.png…]()

**Comment by abi** [comment]
@Hellen20030926 can't see your Docker logs

**Comment by Hellen20030926** [comment]
> 看不到 Docker 日志
Due to the failure of the initial deployment, I have deleted the project with plans for re-deployment. Currently lacking an openAPI, I intend to employ a proxy. How should I go about modifying the settings?

**Comment by abi** [comment]
There's a setting in the settings box to update the OpenAI URL
