### ISSUE TITLE
Exception in ASGI application

### ISSUE THREAD

**Issue by wuxiaolingwu** [abi/screenshot-to-code#141]
INFO:     ('127.0.0.1', 51927) - "WebSocket /generate-code" [accepted]
INFO:     connection open
Using OpenAI API key from client-side settings dialog
generating code...
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\anyio\_core\_sockets.py", line 167, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\anyio\_backends\_asyncio.py", line 1627, in connect_tcp
    await get_running_loop().create_connection(
  File "F:\python\python312\Lib\asyncio\base_events.py", line 1099, in create_connection
    raise exceptions[0]
  File "F:\python\python312\Lib\asyncio\base_events.py", line 1081, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python\python312\Lib\asyncio\base_events.py", line 984, in _connect_sock
    await self.sock_connect(sock, address)
  File "F:\python\python312\Lib\asyncio\selector_events.py", line 647, in sock_connect
    return await fut
           ^^^^^^^^^
  File "F:\python\python312\Lib\asyncio\selector_events.py", line 687, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 10060] Connect call failed ('*****', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpcore\_backends\anyio.py", line 114, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\anyio\_core\_sockets.py", line 225, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpcore\_async\connection_pool.py", line 268, in handle_async_request
    raise exc
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpcore\_async\connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpcore\_async\connection.py", line 99, in handle_async_request
    raise exc
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpcore\_async\connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpcore\_backends\auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpcore\_backends\anyio.py", line 112, in connect_tcp
    with map_exceptions(exc_map):
  File "F:\python\python312\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(value)
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\openai\_base_client.py", line 1299, in _request
    response = await self._client.send(request, auth=self.custom_auth, stream=stream)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "F:\python\python312\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(value)
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\starlette\middleware\cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\fastapi\routing.py", line 289, in app
    await dependant.call(**values)
  File "G:\2023\code\screenshot-to-code-main\backend\main.py", line 117, in stream_code
    completion = await stream_openai_response(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\2023\code\screenshot-to-code-main\backend\llm.py", line 23, in stream_openai_response
    completion = await client.chat.completions.create(**params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\openai\resources\chat\completions.py", line 1191, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\openai\_base_client.py", line 1474, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\openai\_base_client.py", line 1275, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\openai\_base_client.py", line 1329, in _request
    return await self._retry_request(options, cast_to, retries, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\openai\_base_client.py", line 1356, in _retry_request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\openai\_base_client.py", line 1329, in _request
    return await self._retry_request(options, cast_to, retries, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\openai\_base_client.py", line 1356, in _retry_request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\testInfo\AppData\Local\pypoetry\Cache\virtualenvs\backend-v-lDjRCE-py3.12\Lib\site-packages\openai\_base_client.py", line 1330, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
INFO:     connection closed

**Comment by wuxiaolingwu** [comment]
> Same error, have you tried vpn？

I don't have VPN
