### ISSUE TITLE
when backend  run-time failed!

### ISSUE THREAD

**Issue by ptozys** [abi/screenshot-to-code#168]
macos 

poetry run uvicorn main:app --reload --port 7000
/Users/m2pro/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Will watch for changes in these directories: ['/Users/m2pro/web/screenshot-to-code/backend/backend']
INFO:     Uvicorn running on http://127.0.0.1:7000 (Press CTRL+C to quit)
INFO:     Started reloader process [6788] using StatReload
INFO:     Started server process [6792]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     ('127.0.0.1', 57941) - "WebSocket /generate-code" [accepted]
Incoming websocket connection...
INFO:     connection open
Received params
Generating html_tailwind code
Using OpenAI API key from environment variable
Using official OpenAI URL
generating code...
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/starlette/middleware/cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  **File "/Users/m2pro/web/screenshot-to-code/backend/backend/main.py", line 192, in stream_code
    completion = await stream_openai_response(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m2pro/web/screenshot-to-code/backend/backend/llm.py", line 26, in stream_openai_response
    completion = await client.chat.completions.create(**params)**
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 1199, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1542, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1316, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1354, in _request
    return await self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1424, in _retry_request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1354, in _request
    return await self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1424, in _retry_request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/m2pro/Library/Caches/pypoetry/virtualenvs/backend-zf339tcS-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1368, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Error code: 500 - {'error': {'message': 'The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID 2b71dc996666ce411ffb9769f1bb1dc1 in your email.)', 'type': 'server_error', 'param': None, 'code': None}}

==============================================================================

File "/Users/m2pro/web/screenshot-to-code/backend/backend/main.py", line 192, in stream_code
    completion = await stream_openai_response(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m2pro/web/screenshot-to-code/backend/backend/llm.py", line 26, in stream_openai_response
    completion = await client.chat.completions.create(**params)
    
    
hit above two lines

this is  similar troublesome in openai community
https://community.openai.com/t/openai-api-error-the-server-had-an-error-while-processing-your-request-sorry-about-that/53263

**Comment by abi** [comment]
@ptozys can you try again? OpenAI was having some uptime issues that now seem to be resolved: https://status.openai.com/#past-incidents
