### ISSUE TITLE
Connection closed 1006 

### ISSUE THREAD

**Issue by SuperDannyBoy** [abi/screenshot-to-code#259]
**i have a same problem**
i am run in my local computer. this  is my error info  in backend. i am sure i have set the OpenAI API key.

![image](https://github.com/abi/screenshot-to-code/assets/5237197/cb346d8f-e66f-4f92-9d37-0f051a78d8f4)
![image](https://github.com/abi/screenshot-to-code/assets/5237197/dfdfe721-7bea-4c2b-a332-6c7c7b19cd15)
![image](https://github.com/abi/screenshot-to-code/assets/5237197/7c388bcb-9ea7-41d3-9e9e-83a045ed38f0)
![image](https://github.com/abi/screenshot-to-code/assets/5237197/38834a5b-e6cf-46e5-9b96-b26e8186abac)

INFO:     ('127.0.0.1', 3138) - "WebSocket /generate-code" [accepted]
Incoming websocket connection...
INFO:     connection open
Received params
Generating vue_tailwind code for uploaded image using gpt_4_vision model...
Using OpenAI API key from client-side settings dialog
Using official OpenAI URL
generating code...
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\httpcore\_async\http_proxy.py", line 317, in handle_async_request
    stream = await stream.start_tls(**kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\httpcore\_async\http11.py", line 383, in start_tls
    return await self._stream.start_tls(ssl_context, server_hostname, timeout)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\httpcore\_backends\anyio.py", line 66, in start_tls
    with map_exceptions(exc_map):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\openai\_base_client.py", line 1457, in _request
    response = await self._client.send(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 250, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\starlette\middleware\cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\fastapi\routing.py", line 289, in app
    await dependant.call(**values)
  File "D:\AI\screenshot-to-code-main\backend\routes\generate_code.py", line 257, in stream_code
    completion = await stream_openai_response(
  File "D:\AI\screenshot-to-code-main\backend\llm.py", line 38, in stream_openai_response
    stream = await client.chat.completions.create(**params)  # type: ignore
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\openai\resources\chat\completions.py", line 1330, in create
    return await self._post(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\openai\_base_client.py", line 1725, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\openai\_base_client.py", line 1428, in request
    return await self._request(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\openai\_base_client.py", line 1481, in _request
    return await self._retry_request(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\openai\_base_client.py", line 1550, in _retry_request
    return await self._request(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\openai\_base_client.py", line 1481, in _request
    return await self._retry_request(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\openai\_base_client.py", line 1550, in _retry_request
    return await self._request(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\backend-0BbiDr-S-py3.10\lib\site-packages\openai\_base_client.py", line 1491, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
INFO:     connection closed

**Comment by abi** [comment]
openai.APIConnectionError

Does your ISP/country block OpenAI? Have you successfully used the OpenAI api before? If not, you can look into proxies for the API and use the baseURL parameter.

**Comment by SuperDannyBoy** [comment]
> openai.APIConnectionError
> 
> Does your ISP/country block OpenAI? Have you successfully used the OpenAI api before? If not, you can look into proxies for the API and use the baseURL parameter.

you are right! i reset my proxies for the API. It works fine now, thanks!

**Comment by pluto-tu** [comment]
> > openai.APIConnectionError
> > Does your ISP/country block OpenAI? Have you successfully used the OpenAI api before? If not, you can look into proxies for the API and use the baseURL parameter.
> 
> you are right! i reset my proxies for the API. It works fine now, thanks!
@abi @SuperDannyBoy   
Hi ,I can call openai api interface with my api key ,but when i run ,it error.  can you show how did you slove this problem.
pypoetry/virtualenvs/backend-FuQBPevx-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1504, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

**Comment by abi** [comment]
@pluto-tu Hi, please ask these questions in a new issue. With APIConnectionError, your ISP is probably blocking the OpenAI API URL, try a VPN or a proxy.

Locking this issue. Feel free to open a new one.
