### ISSUE TITLE
 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}}

### ISSUE THREAD

**Issue by raphale123** [abi/screenshot-to-code#272]
The model I selected is Claude 3 sonnet, but he reported an error
Raise self_ Make status error from None (err. response)
Anthropic AuthenticationError: Error code: 401- {type ':' error ',' error ': {type': 'authentication_error', 'message': 'invalid x-api-key'}}
![Uploading photo_2024-03-19_16-18-31.jpg…]()

**Comment by abi** [comment]
Can you get a new API key and try that? The error seems to be indicate that you haven't set a correct API key for the ANTHROPIC_API_KEY env var

**Comment by abi** [comment]
Closing due to inactivity

**Comment by IgorKendyS** [comment]
> Can you get a new API key and try that? The error seems to be indicate that you haven't set a correct API key for the ANTHROPIC_API_KEY env var

It works for me, thank you abi

**Comment by keuj6** [comment]
I have the same problem here. I have a ANTHROPIC_API_KEY defined in a .env in my backend folder. But I get the 401 error after uploading a picture on the frontend.

I tried first with a key I generated a week ago or so and got the error. Then I generate a new one, and get the same result.

Here is the error displayed in uvicorn output:

> Error generating code. Please contact support.
> Traceback (most recent call last):
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/llm.py", line 128, in stream_claude_response
>     async with client.messages.stream(
>                ~~~~~~~~~~~~~~~~~~~~~~^
>         model=model.value,
>         ^^^^^^^^^^^^^^^^^^
>     ...<4 lines>...
>         extra_headers={"anthropic-beta": "max-tokens-3-5-sonnet-2024-07-15"},
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     ) as stream:
>     ^
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/anthropic/lib/streaming/_messages.py", line 305, in __aenter__
>     raw_stream = await self.__api_request
>                  ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/anthropic/_base_client.py", line 1838, in post
>     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/anthropic/_base_client.py", line 1532, in request
>     return await self._request(
>            ^^^^^^^^^^^^^^^^^^^^
>     ...<5 lines>...
>     )
>     ^
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/anthropic/_base_client.py", line 1633, in _request
>     raise self._make_status_error_from_response(err.response) from None
> anthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}}
> Traceback (most recent call last):
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/llm.py", line 128, in stream_claude_response
>     async with client.messages.stream(
>                ~~~~~~~~~~~~~~~~~~~~~~^
>         model=model.value,
>         ^^^^^^^^^^^^^^^^^^
>     ...<4 lines>...
>         extra_headers={"anthropic-beta": "max-tokens-3-5-sonnet-2024-07-15"},
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     ) as stream:
>     ^
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/anthropic/lib/streaming/_messages.py", line 305, in __aenter__
>     raw_stream = await self.__api_request
>                  ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/anthropic/_base_client.py", line 1838, in post
>     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/anthropic/_base_client.py", line 1532, in request
>     return await self._request(
>            ^^^^^^^^^^^^^^^^^^^^
>     ...<5 lines>...
>     )
>     ^
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/anthropic/_base_client.py", line 1633, in _request
>     raise self._make_status_error_from_response(err.response) from None
> anthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}}
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 250, in run_asgi
>     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
>     return await self.app(scope, receive, send)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/fastapi/applications.py", line 276, in __call__
>     await super().__call__(scope, receive, send)
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/starlette/applications.py", line 122, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/starlette/middleware/errors.py", line 149, in __call__
>     await self.app(scope, receive, send)
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/starlette/middleware/cors.py", line 75, in __call__
>     await self.app(scope, receive, send)
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
>     raise exc
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
>     await self.app(scope, receive, sender)
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
>     raise e
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
>     await self.app(scope, receive, send)
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/starlette/routing.py", line 718, in __call__
>     await route.handle(scope, receive, send)
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/starlette/routing.py", line 341, in handle
>     await self.app(scope, receive, send)
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/starlette/routing.py", line 82, in app
>     await func(session)
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/.venv/lib/python3.13/site-packages/fastapi/routing.py", line 289, in app
>     await dependant.call(**values)
>   File "Path/To/My/Working/Dir/screenshot-to-code/backend/routes/generate_code.py", line 329, in stream_code
>     raise Exception("All generations failed")
> Exception: All generations failed
> INFO:     connection closed

**Comment by abi** [comment]
@keuj6 where did you get your Anthropic key from?

**Comment by keuj6** [comment]
hi @abi, I created myself from Anthropic concole: https://console.anthropic.com/settings/keys

![image](https://github.com/user-attachments/assets/52283c4c-e201-43ba-b6cb-cbe969ce7682)

**Comment by abi** [comment]
Cool that seems like the right spot. 

I will test it out tomorrow but as far as I know, Anthropic doesn't restrict any models to only certain keys. 

Have you used the keys on any other app? And is the error message in the backend definitely say invalid api key?

**Comment by abushoeb** [comment]
I had the same issue. Running the following code block in a Python Notebook gave me a detailed message about the error. Then, I realized that I needed more credits or payment methods. After loading some credits using a credit card, it started working 😄

```python
import os
from anthropic import Anthropic
from dotenv import load_dotenv

# Load the .env file
load_dotenv()

client = Anthropic(
    # This is the default and can be omitted
    api_key=os.environ.get("ANTHROPIC_API_KEY"),
)

message = client.messages.create(
    max_tokens=1024,
    messages=[
        {
            "role": "user",
            "content": "Hello, Claude",
        }
    ],
    model="claude-3-opus-20240229",
)
print(message.content)
```

**Error message without credits**
```
BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'Your credit balance is too low to access the Anthropic API. Please go to Plans & Billing to upgrade or purchase credits.'}}
```

**Comment by abi** [comment]
Thanks for the fix. Will try to fix the project to emit the clearer error.

**Comment by keuj6** [comment]
@abi , I didn't use the API key elsewhere it is brand new
I am 95% sure that the error code is "invalid: x-api-key" >> I will check this point this evening (~10hrs from now) and report as an update to this comment

I will also try the code snippet above by abushoeb and see if I get the same message or not.

**Comment by abi** [comment]
I just tested a fresh local install with a new Anthropic key and it worked for me so it's probably something specific to your Anthropic account. I know I have no limits on models because I've spent a lot of money with this account.

**Comment by keuj6** [comment]
I will extract the exact header you are using, and insert it in abushoeb script to see what part of it generates the error. I suspect that there is something funky going on with the {"anthropic-beta": "max-tokens-3-5-sonnet-2024-07-15"} part >> I will update

**Comment by keuj6** [comment]
well, i apologize for the fuss, but retrying with the same API key two days later worked w/o me changing any of my configuration. It might have been a delay in key activation on Anthropic side. Thx for the great piece of software!

**Comment by abi** [comment]
Awesome!

**Comment by rmagon** [comment]
Hello again! 

Just adding some context here:

I was getting the same error recently, when i turned on `litellm._turn_on_debug()` I realized that litellm was sending the `OPENAI_API_KEY` to the anthropic API instead of the `ANTHROPIC_API_KEY`.

My .env looked like this:
```
MODEL=claude-3-5-sonnet-20241022
ANTHROPIC_API_KEY=<anthropic key>
OPENAI_API_KEY=<openapi key>
```

Removing the `OPENAI_API_KEY` from env did the trick.
