### ISSUE TITLE
There is a way to use it from CLI?

### ISSUE THREAD

**Issue by Test67766** [abi/screenshot-to-code#280]
I appreciate your work, there is a way to use it from command line?

**Comment by abi** [comment]
There isn't but if someone wants to submit a PR, happy to include it.

**Comment by Test67766** [comment]
okay i will try

**Comment by abi** [comment]
I'd appreciate it if it didn't refactor the code too much (harder to review PR). There is a eval script that does run the generate code functionality in bulk from CLI: https://github.com/abi/screenshot-to-code/blob/main/Evaluation.md

**Comment by Test67766** [comment]
I have add the STACK var but (i have defined at start an OpenAPi on .env fie):

python3 run_evals.py
Traceback (most recent call last):
  File "/home/glande/Desktop/screenshot-to-code/backend/run_evals.py", line 43, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/*****/Desktop/screenshot-to-code/backend/run_evals.py", line 31, in main
    results = await asyncio.gather(*tasks)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/*****/Desktop/screenshot-to-code/backend/evals/core.py", line 21, in generate_code_core
    if not anthropic_api_key:
           ^^^^^^^^^^^^^^^^^
NameError: name 'anthropic_api_key' is not defined

**Comment by abi** [comment]
You probably just need to set that env var

**Comment by hoanghohotel** [comment]
https://v0.dev/
It free from https://vercel.com/
