### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by yashk1998** [abi/screenshot-to-code#281]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Side Hustle\Code\venv\Lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started     
    target(sockets=sockets)
  File "D:\Side Hustle\Code\venv\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Side Hustle\Code\venv\Lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "D:\Side Hustle\Code\venv\Lib\site-packages\uvicorn\config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Side Hustle\Code\venv\Lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Side Hustle\Code\screenshot\backend\main.py", line 4, in <module>
    load_dotenv()
  File "D:\Side Hustle\Code\venv\Lib\site-packages\dotenv\main.py", line 356, in load_dotenv
    return dotenv.set_as_environment_variables()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Side Hustle\Code\venv\Lib\site-packages\dotenv\main.py", line 92, in set_as_environment_variables
    if not self.dict():
           ^^^^^^^^^^^
  File "D:\Side Hustle\Code\venv\Lib\site-packages\dotenv\main.py", line 76, in dict
    self._dict = OrderedDict(resolve_variables(raw_values, override=self.override))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Side Hustle\Code\venv\Lib\site-packages\dotenv\main.py", line 238, in resolve_variables
    for (name, value) in values:
  File "D:\Side Hustle\Code\venv\Lib\site-packages\dotenv\main.py", line 84, in parse
    for mapping in with_warn_for_invalid_lines(parse_stream(stream)):
  File "D:\Side Hustle\Code\venv\Lib\site-packages\dotenv\main.py", line 26, in with_warn_for_invalid_lines
    for mapping in mappings:
  File "D:\Side Hustle\Code\venv\Lib\site-packages\dotenv\parser.py", line 173, in parse_stream
    reader = Reader(stream)
             ^^^^^^^^^^^^^^
  File "D:\Side Hustle\Code\venv\Lib\site-packages\dotenv\parser.py", line 64, in __init__
    self.string = stream.read()
                  ^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode

**Comment by abi** [comment]
This might fix your issue: https://github.com/abi/screenshot-to-code/issues/161

**Comment by yashk1998** [comment]
Thanks, man. Appreciate it.
