### ISSUE TITLE
Why is it invalid to clone the URL directly, I have filled in and configured the apikey correctly

### ISSUE THREAD

**Issue by wshwhyu** [abi/screenshot-to-code#309]
![image](https://github.com/abi/screenshot-to-code/assets/16811625/3f390e22-9173-4af3-b2f9-71c9e6e8f1fd)

**Comment by wshwhyu** [comment]
Another question is that if you put a screenshot in it, you can't recognize the image with this model GPT-4 Turbo (Apr 2024), but you can recognize and generate web pages with this model GPT-4 Vision (Nov 2023). The front and back ends are configured correctly.  
![image](https://github.com/abi/screenshot-to-code/assets/16811625/8f6f5b1c-0a5c-4b9d-803b-c6fdf406adf2)

**Comment by abi** [comment]
You need a separate API key from https://screenshotone.com/ to take screenshots.

Your second question - I'm not sure I fully understand you. GPT-4 Vision (Nov 2023) works for you but GPT-4 Turbo (Apr 2024) doesn't? What's the error you see on the backend logs when you use GPT-4 Turbo (Apr 2024)?

**Comment by wshwhyu** [comment]
The first problem: when using the GPT-4 Vision (Nov 2023) model, the same API can generate code, but it is not possible to generate code by entering URL.
The second problem: when using the same API and using the GPT-4 Vision (Nov 2023) model, you can generate the code, but when you switch the model to GPT-4 Turbo (Apr 2024), an error will be reported, and the code cannot be generated

**Comment by wshwhyu** [comment]
The API key is there, and it is also set, and the diagram code can be realized, but no matter which model is switched, when the input is URL, an error will be reported, showing "Please add a ScreenshotOne API key in the Settings dialog. This is optional you can also drag/drop and upload images directly.”

**Comment by wshwhyu** [comment]
(backend-py3.11) E:\screenshot-to-code\backend>poetry run uvicorn main:app --reload --port 7001
[32mINFO[0m:     Will watch for changes in these directories: ['E:\\screenshot-to-code\\backend']
[32mINFO[0m:     Uvicorn running on [1mhttp://127.0.0.1:7001[0m (Press CTRL+C to quit)
[32mINFO[0m:     Started reloader process [[36m[1m34780[0m] using [36m[1mStatReload[0m
[32mINFO[0m:     Started server process [[36m34092[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     127.0.0.1:11268 - "[1mPOST /api/screenshot HTTP/1.1[0m" [91m500 Internal Server Error[0m
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 40
8, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 8
4, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\fastapi\applications.py", line 276, in __cal
l__
    await super().__call__(scope, receive, send)
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\starlette\applications.py", line 122, in __c
all__
    await self.middleware_stack(scope, receive, send)
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\starlette\middleware\errors.py", line 184, i
n __call__
    raise exc
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\starlette\middleware\errors.py", line 162, i
n __call__
    await self.app(scope, receive, _send)
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\starlette\middleware\cors.py", line 91, in _
_call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\starlette\middleware\cors.py", line 146, in
simple_response
    await self.app(scope, receive, send)
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\starlette\middleware\exceptions.py", line 79
, in __call__
    raise exc
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\starlette\middleware\exceptions.py", line 68
, in __call__
    await self.app(scope, receive, sender)
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line
21, in __call__
    raise e
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line
18, in __call__
    await self.app(scope, receive, send)
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\starlette\routing.py", line 718, in __call__

    await route.handle(scope, receive, send)
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\poetryPath\Virtualenvs\backend-OlPcJNFD-py3.11\Lib\site-packages\fastapi\routing.py", line 163, in run_endpoi
nt_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\screenshot-to-code\backend\routes\screenshot.py", line 61, in app_screenshot
    image_bytes = await capture_screenshot(url, api_key=api_key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\screenshot-to-code\backend\routes\screenshot.py", line 42, in capture_screenshot
    raise Exception("Error taking screenshot")
Exception: Error taking screenshot

**Comment by abi** [comment]
@wshwhyu does it work now?

**Comment by abi** [comment]
Closing due to inactivity
