### ISSUE TITLE
After uploading the image, the backend service shows that the connection is closed directly, but it is normal to check the script file, I hope to know the reason.

### ISSUE THREAD

**Issue by eachann1024** [abi/screenshot-to-code#335]
In fact, the GPT API request was not sent correctly, as I can see from the API logs.
![Image_2024-05-20_16-56-23](https://github.com/abi/screenshot-to-code/assets/43348055/1c5ba7fb-a0fa-4599-a6d0-d0564592f514)
![Image_2024-05-20_16-56-29](https://github.com/abi/screenshot-to-code/assets/43348055/930dacbe-627f-4979-b420-4b4472f174f6)
[messages_20240520_165023.json](https://github.com/abi/screenshot-to-code/files/15374978/messages_20240520_165023.json)

**Comment by eachann1024** [comment]
![image](https://github.com/abi/screenshot-to-code/assets/43348055/6b974c4c-af63-44ea-bd21-606f9bcd9167)

**Comment by abi** [comment]
Hi based on your logs. It looks like the request was sent and completed correctly. What's the problem you're seeing? Is the code not showing up on the frontend?

**Comment by prestonator** [comment]
@abi I know for me, when I try to use the new gpt-4o with React + Tailwind, it just spits out the same code and same web page, titled "Reference Website". When switching to gpt-4-vision, it generates the code properly.

**Comment by prestonator** [comment]
But I use OpenRouter as my OpenAI endpoint, I don't think this makes a difference though.

**Comment by prestonator** [comment]
```javascript
<html>
<head>
    <title>Reference Web Page</title>
    <script src="https://unpkg.com/react/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.js"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"></link>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
        }
    </style>
</head>
<body class="bg-gray-100">
    <div id="root"></div>
    <script type="text/babel">
        const App = () => {
            return (
                <div className="container mx-auto p-4">
                    <header className="bg-white shadow-md p-4 flex justify-between items-center">
                        <h1 className="text-2xl font-bold text-gray-800">Website Title</h1>
                        <nav>
                            <ul className="flex space-x-4">
                                <li><a href="#" className="text-gray-600 hover:text-gray-800">Home</a></li>
                                <li><a href="#" className="text-gray-600 hover:text-gray-800">About</a></li>
                                <li><a href="#" className="text-gray-600 hover:text-gray-800">Services</a></li>
                                <li><a href="#" className="text-gray-600 hover:text-gray-800">Contact</a></li>
                            </ul>
                        </nav>
                    </header>
                    <main className="mt-6">
                        <section className="bg-white p-6 rounded-lg shadow-md">
                            <h2 className="text-xl font-bold text-gray-800 mb-4">Section Title</h2>
                            <p className="text-gray-600 mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.</p>
                            <button className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">Read More</button>
                        </section>
                        <section className="mt-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                            <div className="bg-white p-4 rounded-lg shadow-md">
                                <img src="https://placehold.co/300x200" alt="Placeholder image 1" className="w-full h-48 object-cover rounded-t-lg"/>
                                <h3 className="text-lg font-bold text-gray-800 mt-4">Card Title 1</h3>
                                <p className="text-gray-600 mt-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            </div>
                            <div className="bg-white p-4 rounded-lg shadow-md">
                                <img src="https://placehold.co/300x200" alt="Placeholder image 2" className="w-full h-48 object-cover rounded-t-lg"/>
                                <h3 className="text-lg font-bold text-gray-800 mt-4">Card Title 2</h3>
                                <p className="text-gray-600 mt-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            </div>
                            <div className="bg-white p-4 rounded-lg shadow-md">
                                <img src="https://placehold.co/300x200" alt="Placeholder image 3" className="w-full h-48 object-cover rounded-t-lg"/>
                                <h3 className="text-lg font-bold text-gray-800 mt-4">Card Title 3</h3>
                                <p className="text-gray-600 mt-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            </div>
                        </section>
                    </main>
                    <footer className="bg-white shadow-md p-4 mt-6 text-center">
                        <p className="text-gray-600">&copy; 2023 Website Title. All rights reserved.</p>
                    </footer>
                </div>
            );
        };

        ReactDOM.render(<App />, document.getElementById('root'));
    </script>
</body>
</html>
```

**Comment by abi** [comment]
@prestonator I can take a closer look at this. Usually when this happens, the issue is that the image isn't uploaded properly. What environment are you running your code in? Locally?

**Comment by eachann1024** [comment]
> Hi based on your logs. It looks like the request was sent and completed correctly. What's the problem you're seeing? Is the code not showing up on the frontend?

![image](https://github.com/abi/screenshot-to-code/assets/43348055/83c15f23-1dec-4711-8459-3cbfbb8a44b7)
![image](https://github.com/abi/screenshot-to-code/assets/43348055/d09cddbd-86ad-4875-9499-ab10b7396372)
![image](https://github.com/abi/screenshot-to-code/assets/43348055/2140ed10-1ec3-4d0e-a1e7-cfe1e9690772)

The problem is: no matter what model I use or what language I generate, I end up with a closed connection in the console, I check the gpt api credits and they are not deducted, and the generated code is blank.

**Comment by eachann1024** [comment]
> Hi based on your logs. It looks like the request was sent and completed correctly. What's the problem you're seeing? Is the code not showing up on the frontend?

https://github.com/abi/screenshot-to-code/assets/43348055/e83b0773-9d6c-4d94-bd1e-feb3887d7bd2

**Comment by abi** [comment]
@eachann1024 Thanks for the video. Still not sure what the problem is. Are you using a proxy or OpenAI directly? To isolate the problem further, can you tried Claude with an Anthropic key?

**Comment by LLMFocus** [comment]
For me it was because of proxy. Once the proxy is off, the connection close error stops.

**Comment by cobolbaby** [comment]
```
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 250, in run_asgi
backend_1   |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
backend_1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_1   |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
backend_1   |     return await self.app(scope, receive, send)
backend_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 276, in __call__
backend_1   |     await super().__call__(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 122, in __call__
backend_1   |     await self.middleware_stack(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 149, in __call__
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 75, in __call__
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend_1   |     raise exc
backend_1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend_1   |     await self.app(scope, receive, sender)
backend_1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend_1   |     raise e
backend_1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 718, in __call__
backend_1   |     await route.handle(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 341, in handle
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 82, in app
backend_1   |     await func(session)
backend_1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 289, in app
backend_1   |     await dependant.call(**values)
backend_1   |   File "/app/routes/generate_code.py", line 268, in stream_code
backend_1   |     completion = await stream_openai_response(
backend_1   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_1   |   File "/app/llm.py", line 62, in stream_openai_response
backend_1   |     stream = await client.chat.completions.create(**params)  # type: ignore
backend_1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_1   |   File "/usr/local/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 1334, in create
backend_1   |     return await self._post(
backend_1   |            ^^^^^^^^^^^^^^^^^
backend_1   |   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1738, in post
backend_1   |     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
backend_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_1   |   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1441, in request
backend_1   |     return await self._request(
backend_1   |            ^^^^^^^^^^^^^^^^^^^^
backend_1   |   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1532, in _request
backend_1   |     raise self._make_status_error_from_response(err.response) from None
backend_1   | openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': "[{'loc': ('body', 'messages'), 'msg': 'str type expected', 'type': 'type_error.str'}, {'loc': ('body', 'messages', 1, 'content'), 'msg': 'str type expected', 'type': 'type_error.str'}]", 'code': 40001}
backend_1   | INFO:     connection closed
```
