### ISSUE TITLE
backend server runs with errors

### ISSUE THREAD

**Issue by gyxter** [abi/screenshot-to-code#343]
Any idea why this is happening?

```
(backend-py3.10) PS C:\screenshot-to-code\backend> poetry run uvicorn main:app --reload --port 7001
INFO:     Will watch for changes in these directories: ['C:\\screenshot-to-code\\backend']
INFO:     Uvicorn running on http://127.0.0.1:7001 (Press CTRL+C to quit)
INFO:     Started reloader process [15952] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\gyxte\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\gyxte\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\gyxte\AppData\Local\pypoetry\Cache\virtualenvs\backend-RpSLUTQm-py3.10\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\gyxte\AppData\Local\pypoetry\Cache\virtualenvs\backend-RpSLUTQm-py3.10\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\gyxte\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\gyxte\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\gyxte\AppData\Local\pypoetry\Cache\virtualenvs\backend-RpSLUTQm-py3.10\lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\Users\gyxte\AppData\Local\pypoetry\Cache\virtualenvs\backend-RpSLUTQm-py3.10\lib\site-packages\uvicorn\config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\gyxte\AppData\Local\pypoetry\Cache\virtualenvs\backend-RpSLUTQm-py3.10\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\gyxte\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\screenshot-to-code\backend\main.py", line 9, in <module>
    from routes import screenshot, generate_code, home, evals
  File "C:\screenshot-to-code\backend\routes\generate_code.py", line 25, in <module>
    from video.utils import extract_tag_content, assemble_claude_prompt_video
  File "C:\screenshot-to-code\backend\video\utils.py", line 10, in <module>
    from PIL import Image
  File "C:\Users\gyxte\AppData\Local\Programs\Python\Python310\lib\PIL\Image.py", line 84, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\gyxte\AppData\Local\Programs\Python\Python310\lib\PIL\__init__.py)
```

**Comment by abi** [comment]
That is strange.

Are you using the video feature or just screenshots?

I think the core issue with installing PIL correctly on your system so you could try deleting this folder, and re-cloning and re-installing.

And here's some ChatGPT suggestions on what to do: https://chatgpt.com/share/e4e9a634-a831-45c0-a398-5548ca31ccb0

Let me know if any of these work.

**Comment by gyxter** [comment]
Just screenshot.
