### ISSUE TITLE
Error Generating Code Backend Service Down

### ISSUE THREAD

**Issue by Lbazzi** [abi/screenshot-to-code#361]
**Describe the bug**
Error Generating Code

**To Reproduce**
1. Use docker-compose to run the project
2. Backend's status is Exited
3. 2024-06-14 23:45:31 Skipping virtualenv creation, as specified in config file.
2024-06-14 23:45:31 Traceback (most recent call last):
2024-06-14 23:45:31   File "/usr/local/bin/uvicorn", line 8, in <module>
2024-06-14 23:45:31     sys.exit(main())
2024-06-14 23:45:31              ^^^^^^
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
2024-06-14 23:45:31     return self.main(*args, **kwargs)
2024-06-14 23:45:31            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
2024-06-14 23:45:31     rv = self.invoke(ctx)
2024-06-14 23:45:31          ^^^^^^^^^^^^^^^^
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
2024-06-14 23:45:31     return ctx.invoke(self.callback, **ctx.params)
2024-06-14 23:45:31            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
2024-06-14 23:45:31     return __callback(*args, **kwargs)
2024-06-14 23:45:31            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 416, in main
2024-06-14 23:45:31     run(
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 587, in run
2024-06-14 23:45:31     server.run()
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 61, in run
2024-06-14 23:45:31     return asyncio.run(self.serve(sockets=sockets))
2024-06-14 23:45:31            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
2024-06-14 23:45:31     return runner.run(main)
2024-06-14 23:45:31            ^^^^^^^^^^^^^^^^
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
2024-06-14 23:45:31     return self._loop.run_until_complete(task)
2024-06-14 23:45:31            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
2024-06-14 23:45:31     return future.result()
2024-06-14 23:45:31            ^^^^^^^^^^^^^^^
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 68, in serve
2024-06-14 23:45:31     config.load()
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/uvicorn/config.py", line 467, in load
2024-06-14 23:45:31     self.loaded_app = import_from_string(self.app)
2024-06-14 23:45:31                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/uvicorn/importer.py", line 21, in import_from_string
2024-06-14 23:45:31     module = importlib.import_module(module_str)
2024-06-14 23:45:31              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
2024-06-14 23:45:31     return _bootstrap._gcd_import(name[level:], package, level)
2024-06-14 23:45:31            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-14 23:45:31   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2024-06-14 23:45:31   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2024-06-14 23:45:31   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2024-06-14 23:45:31   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2024-06-14 23:45:31   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
2024-06-14 23:45:31   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2024-06-14 23:45:31   File "/app/main.py", line 7, in <module>
2024-06-14 23:45:31     from fastapi import FastAPI
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/fastapi/__init__.py", line 7, in <module>
2024-06-14 23:45:31     from .applications import FastAPI as FastAPI
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 16, in <module>
2024-06-14 23:45:31     from fastapi import routing
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 24, in <module>
2024-06-14 23:45:31     from fastapi.dependencies.models import Dependant
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/fastapi/dependencies/models.py", line 3, in <module>
2024-06-14 23:45:31     from fastapi.security.base import SecurityBase
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/fastapi/security/__init__.py", line 1, in <module>
2024-06-14 23:45:31     from .api_key import APIKeyCookie as APIKeyCookie
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/fastapi/security/api_key.py", line 3, in <module>
2024-06-14 23:45:31     from fastapi.openapi.models import APIKey, APIKeyIn
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/fastapi/openapi/models.py", line 103, in <module>
2024-06-14 23:45:31     class Schema(BaseModel):
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 286, in __new__
2024-06-14 23:45:31     cls.__try_update_forward_refs__()
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 807, in __try_update_forward_refs__
2024-06-14 23:45:31     update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/pydantic/typing.py", line 554, in update_model_forward_refs
2024-06-14 23:45:31     update_field_forward_refs(f, globalns=globalns, localns=localns)
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/pydantic/typing.py", line 520, in update_field_forward_refs
2024-06-14 23:45:31     field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
2024-06-14 23:45:31                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-14 23:45:31   File "/usr/local/lib/python3.12/site-packages/pydantic/typing.py", line 66, in evaluate_forwardref
2024-06-14 23:45:31     return cast(Any, type_)._evaluate(globalns, localns, set())
2024-06-14 23:45:31            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-14 23:45:31 TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

**Screenshots of backend AND frontend terminal logs**
<img width="1032" alt="image" src="https://github.com/abi/screenshot-to-code/assets/50550412/c1ad0d8c-0664-4501-afe7-579102563669">
<img width="1037" alt="image" src="https://github.com/abi/screenshot-to-code/assets/50550412/ee2b0071-b798-43a2-9b79-493485d77c68">

**Comment by abi** [comment]
Could you use the change from this PR? https://github.com/abi/screenshot-to-code/pull/358

**Comment by Lbazzi** [comment]
Thanks, it's all fixed now.
