### ISSUE TITLE
User Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue

### ISSUE THREAD

**Issue by yujiyuan** [abi/screenshot-to-code#364]
```
2024-06-21 14:52:18 Skipping virtualenv creation, as specified in config file.
2024-06-21 14:52:18 Traceback (most recent call last):
2024-06-21 14:52:18   File "/usr/local/bin/uvicorn", line 8, in <module>
2024-06-21 14:52:18     sys.exit(main())
2024-06-21 14:52:18              ^^^^^^
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
2024-06-21 14:52:18     return self.main(*args, **kwargs)
2024-06-21 14:52:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
2024-06-21 14:52:18     rv = self.invoke(ctx)
2024-06-21 14:52:18          ^^^^^^^^^^^^^^^^
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
2024-06-21 14:52:18     return ctx.invoke(self.callback, **ctx.params)
2024-06-21 14:52:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
2024-06-21 14:52:18     return __callback(*args, **kwargs)
2024-06-21 14:52:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 416, in main
2024-06-21 14:52:18     run(
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 587, in run
2024-06-21 14:52:18     server.run()
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 61, in run
2024-06-21 14:52:18     return asyncio.run(self.serve(sockets=sockets))
2024-06-21 14:52:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
2024-06-21 14:52:18     return runner.run(main)
2024-06-21 14:52:18            ^^^^^^^^^^^^^^^^
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
2024-06-21 14:52:18     return self._loop.run_until_complete(task)
2024-06-21 14:52:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
2024-06-21 14:52:18     return future.result()
2024-06-21 14:52:18            ^^^^^^^^^^^^^^^
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 68, in serve
2024-06-21 14:52:18     config.load()
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/uvicorn/config.py", line 467, in load
2024-06-21 14:52:18     self.loaded_app = import_from_string(self.app)
2024-06-21 14:52:18                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/uvicorn/importer.py", line 21, in import_from_string
2024-06-21 14:52:18     module = importlib.import_module(module_str)
2024-06-21 14:52:18              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
2024-06-21 14:52:18     return _bootstrap._gcd_import(name[level:], package, level)
2024-06-21 14:52:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:52:18   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2024-06-21 14:52:18   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2024-06-21 14:52:18   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2024-06-21 14:52:18   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2024-06-21 14:52:18   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
2024-06-21 14:52:18   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2024-06-21 14:52:18   File "/app/main.py", line 7, in <module>
2024-06-21 14:52:18     from fastapi import FastAPI
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/fastapi/__init__.py", line 7, in <module>
2024-06-21 14:52:18     from .applications import FastAPI as FastAPI
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 16, in <module>
2024-06-21 14:52:18     from fastapi import routing
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 24, in <module>
2024-06-21 14:52:18     from fastapi.dependencies.models import Dependant
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/fastapi/dependencies/models.py", line 3, in <module>
2024-06-21 14:52:18     from fastapi.security.base import SecurityBase
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/fastapi/security/__init__.py", line 1, in <module>
2024-06-21 14:52:18     from .api_key import APIKeyCookie as APIKeyCookie
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/fastapi/security/api_key.py", line 3, in <module>
2024-06-21 14:52:18     from fastapi.openapi.models import APIKey, APIKeyIn
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/fastapi/openapi/models.py", line 103, in <module>
2024-06-21 14:52:18     class Schema(BaseModel):
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 286, in __new__
2024-06-21 14:52:18     cls.__try_update_forward_refs__()
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 807, in __try_update_forward_refs__
2024-06-21 14:52:18     update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/pydantic/typing.py", line 554, in update_model_forward_refs
2024-06-21 14:52:18     update_field_forward_refs(f, globalns=globalns, localns=localns)
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/pydantic/typing.py", line 520, in update_field_forward_refs
2024-06-21 14:52:18     field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
2024-06-21 14:52:18                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:52:18   File "/usr/local/lib/python3.12/site-packages/pydantic/typing.py", line 66, in evaluate_forwardref
2024-06-21 14:52:18     return cast(Any, type_)._evaluate(globalns, localns, set())
2024-06-21 14:52:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:52:18 TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
2024-06-21 14:55:04 Skipping virtualenv creation, as specified in config file.
2024-06-21 14:55:04 Traceback (most recent call last):
2024-06-21 14:55:04   File "/usr/local/bin/uvicorn", line 8, in <module>
2024-06-21 14:55:04     sys.exit(main())
2024-06-21 14:55:04              ^^^^^^
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
2024-06-21 14:55:04     return self.main(*args, **kwargs)
2024-06-21 14:55:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
2024-06-21 14:55:04     rv = self.invoke(ctx)
2024-06-21 14:55:04          ^^^^^^^^^^^^^^^^
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
2024-06-21 14:55:04     return ctx.invoke(self.callback, **ctx.params)
2024-06-21 14:55:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
2024-06-21 14:55:04     return __callback(*args, **kwargs)
2024-06-21 14:55:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 416, in main
2024-06-21 14:55:04     run(
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 587, in run
2024-06-21 14:55:04     server.run()
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 61, in run
2024-06-21 14:55:04     return asyncio.run(self.serve(sockets=sockets))
2024-06-21 14:55:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
2024-06-21 14:55:04     return runner.run(main)
2024-06-21 14:55:04            ^^^^^^^^^^^^^^^^
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
2024-06-21 14:55:04     return self._loop.run_until_complete(task)
2024-06-21 14:55:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
2024-06-21 14:55:04     return future.result()
2024-06-21 14:55:04            ^^^^^^^^^^^^^^^
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 68, in serve
2024-06-21 14:55:04     config.load()
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/uvicorn/config.py", line 467, in load
2024-06-21 14:55:04     self.loaded_app = import_from_string(self.app)
2024-06-21 14:55:04                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/uvicorn/importer.py", line 21, in import_from_string
2024-06-21 14:55:04     module = importlib.import_module(module_str)
2024-06-21 14:55:04              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
2024-06-21 14:55:04     return _bootstrap._gcd_import(name[level:], package, level)
2024-06-21 14:55:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:55:04   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2024-06-21 14:55:04   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2024-06-21 14:55:04   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2024-06-21 14:55:04   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2024-06-21 14:55:04   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
2024-06-21 14:55:04   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2024-06-21 14:55:04   File "/app/main.py", line 7, in <module>
2024-06-21 14:55:04     from fastapi import FastAPI
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/fastapi/__init__.py", line 7, in <module>
2024-06-21 14:55:04     from .applications import FastAPI as FastAPI
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 16, in <module>
2024-06-21 14:55:04     from fastapi import routing
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 24, in <module>
2024-06-21 14:55:04     from fastapi.dependencies.models import Dependant
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/fastapi/dependencies/models.py", line 3, in <module>
2024-06-21 14:55:04     from fastapi.security.base import SecurityBase
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/fastapi/security/__init__.py", line 1, in <module>
2024-06-21 14:55:04     from .api_key import APIKeyCookie as APIKeyCookie
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/fastapi/security/api_key.py", line 3, in <module>
2024-06-21 14:55:04     from fastapi.openapi.models import APIKey, APIKeyIn
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/fastapi/openapi/models.py", line 103, in <module>
2024-06-21 14:55:04     class Schema(BaseModel):
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 286, in __new__
2024-06-21 14:55:04     cls.__try_update_forward_refs__()
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 807, in __try_update_forward_refs__
2024-06-21 14:55:04     update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/pydantic/typing.py", line 554, in update_model_forward_refs
2024-06-21 14:55:04     update_field_forward_refs(f, globalns=globalns, localns=localns)
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/pydantic/typing.py", line 520, in update_field_forward_refs
2024-06-21 14:55:04     field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
2024-06-21 14:55:04                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:55:04   File "/usr/local/lib/python3.12/site-packages/pydantic/typing.py", line 66, in evaluate_forwardref
2024-06-21 14:55:04     return cast(Any, type_)._evaluate(globalns, localns, set())
2024-06-21 14:55:04            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 14:55:04 TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
2024-06-21 15:02:28 Skipping virtualenv creation, as specified in config file.
2024-06-21 15:02:28 Traceback (most recent call last):
2024-06-21 15:02:28   File "/usr/local/bin/uvicorn", line 8, in <module>
2024-06-21 15:02:28     sys.exit(main())
2024-06-21 15:02:28              ^^^^^^
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
2024-06-21 15:02:28     return self.main(*args, **kwargs)
2024-06-21 15:02:28            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
2024-06-21 15:02:28     rv = self.invoke(ctx)
2024-06-21 15:02:28          ^^^^^^^^^^^^^^^^
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
2024-06-21 15:02:28     return ctx.invoke(self.callback, **ctx.params)
2024-06-21 15:02:28            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
2024-06-21 15:02:28     return __callback(*args, **kwargs)
2024-06-21 15:02:28            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 416, in main
2024-06-21 15:02:28     run(
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 587, in run
2024-06-21 15:02:28     server.run()
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 61, in run
2024-06-21 15:02:28     return asyncio.run(self.serve(sockets=sockets))
2024-06-21 15:02:28            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
2024-06-21 15:02:28     return runner.run(main)
2024-06-21 15:02:28            ^^^^^^^^^^^^^^^^
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
2024-06-21 15:02:28     return self._loop.run_until_complete(task)
2024-06-21 15:02:28            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
2024-06-21 15:02:28     return future.result()
2024-06-21 15:02:28            ^^^^^^^^^^^^^^^
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 68, in serve
2024-06-21 15:02:28     config.load()
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/uvicorn/config.py", line 467, in load
2024-06-21 15:02:28     self.loaded_app = import_from_string(self.app)
2024-06-21 15:02:28                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/uvicorn/importer.py", line 21, in import_from_string
2024-06-21 15:02:28     module = importlib.import_module(module_str)
2024-06-21 15:02:28              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
2024-06-21 15:02:28     return _bootstrap._gcd_import(name[level:], package, level)
2024-06-21 15:02:28            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 15:02:28   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2024-06-21 15:02:28   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2024-06-21 15:02:28   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2024-06-21 15:02:28   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2024-06-21 15:02:28   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
2024-06-21 15:02:28   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2024-06-21 15:02:28   File "/app/main.py", line 7, in <module>
2024-06-21 15:02:28     from fastapi import FastAPI
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/fastapi/__init__.py", line 7, in <module>
2024-06-21 15:02:28     from .applications import FastAPI as FastAPI
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 16, in <module>
2024-06-21 15:02:28     from fastapi import routing
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 24, in <module>
2024-06-21 15:02:28     from fastapi.dependencies.models import Dependant
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/fastapi/dependencies/models.py", line 3, in <module>
2024-06-21 15:02:28     from fastapi.security.base import SecurityBase
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/fastapi/security/__init__.py", line 1, in <module>
2024-06-21 15:02:28     from .api_key import APIKeyCookie as APIKeyCookie
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/fastapi/security/api_key.py", line 3, in <module>
2024-06-21 15:02:28     from fastapi.openapi.models import APIKey, APIKeyIn
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/fastapi/openapi/models.py", line 103, in <module>
2024-06-21 15:02:28     class Schema(BaseModel):
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 286, in __new__
2024-06-21 15:02:28     cls.__try_update_forward_refs__()
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 807, in __try_update_forward_refs__
2024-06-21 15:02:28     update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/pydantic/typing.py", line 554, in update_model_forward_refs
2024-06-21 15:02:28     update_field_forward_refs(f, globalns=globalns, localns=localns)
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/pydantic/typing.py", line 520, in update_field_forward_refs
2024-06-21 15:02:28     field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
2024-06-21 15:02:28                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 15:02:28   File "/usr/local/lib/python3.12/site-packages/pydantic/typing.py", line 66, in evaluate_forwardref
2024-06-21 15:02:28     return cast(Any, type_)._evaluate(globalns, localns, set())
2024-06-21 15:02:28            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-21 15:02:28 TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
```

The same error is reported on the front-end page, but the backend startup log shows the error shown in the figure
system: macos14.3.1

**Comment by abi** [comment]
Try the fix in this PR: https://github.com/abi/screenshot-to-code/pull/358

**Comment by yujiyuan** [comment]
Well. thank you

**Comment by abi** [comment]
Feel free to re-open if it's still not working.
