### ISSUE TITLE
Error generating code. 

### ISSUE THREAD

**Issue by xcc19960111** [abi/screenshot-to-code#412]
File "D:\Users\xucha\Desktop\screenshot-to-code-main\venv\Lib\site-packages\openai\_base_client.py", line 1532, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4o-2024-05-13` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Users\xucha\Desktop\screenshot-to-code-main\venv\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 250, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\xucha\Desktop\screenshot-to-code-main\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\xucha\Desktop\screenshot-to-code-main\venv\Lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)

**Comment by xcc19960111** [comment]
what's happened

**Comment by xcc19960111** [comment]
'The model `gpt-4o-2024-05-13` does not exist or you do not have access to it.

**Comment by abi** [comment]
Please see the FAQ for how to set up your OpenAi keys. You probably need to buy a little bit of credit.

**Comment by xcc19960111** [comment]
Which model can I use for free?

**Comment by pagnkelly** [comment]
没有外国卡真难受
