### ISSUE TITLE
ws://127.0.0.1:7001/generate-code' failed:

### ISSUE THREAD

**Issue by prithviraju1369** [abi/screenshot-to-code#414]
**Describe the bug**

**To Reproduce**
1. Installed Python 3.13.0 (v3.13.0:60403a5409f, Oct  7 2024, 00:37:40) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
2. backend installation failes at pillow package (pillow = "^10.3.0", types-pillow = "^10.2.0.20240520")
3.  Upon couple of changes to pillow version, install didn't throw error
4. Here is the error with ^10.3.0  Downgrading pillow (10.4.0 -> 10.3.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
      main()
      ~~~~^^
    File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/p8/nwlwtbbj3n7glckm4qzym8v80000gn/T/tmplruqmair/.venv/lib/python3.13/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/p8/nwlwtbbj3n7glckm4qzym8v80000gn/T/tmplruqmair/.venv/lib/python3.13/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
      self.run_setup()
      ~~~~~~~~~~~~~~^^
    File "/private/var/folders/p8/nwlwtbbj3n7glckm4qzym8v80000gn/T/tmplruqmair/.venv/lib/python3.13/site-packages/setuptools/build_meta.py", line 318, in run_setup
      exec(code, locals())
      ~~~~^^^^^^^^^^^^^^^^
    File "<string>", line 33, in <module>
    File "<string>", line 27, in get_version
  KeyError: '__version__'
  

  at /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pillow (10.3.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "pillow (==10.3.0)"'.
5. installed with 11.0.0 but with below warning

Installing the current project: backend (0.1.0)
Warning: The current project could not be installed: No file/folder found for package backend
If you do not want to install the current project use --no-root.
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
In a future version of Poetry this warning will become an error!

6. Upon, poetry run uvicorn main:app --reload --port 7001, get below errors

INFO:     Uvicorn running on http://127.0.0.1:7001 (Press CTRL+C to quit)
INFO:     Started reloader process [11760] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
    ~~~~~~~~~~~^^
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/prithvirajuuppalapati/Desktop/screenshot-to-code/backend/main.py", line 7, in <module>
    from fastapi import FastAPI
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/fastapi/routing.py", line 24, in <module>
    from fastapi.dependencies.models import Dependant
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/fastapi/dependencies/models.py", line 3, in <module>
    from fastapi.security.base import SecurityBase
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/fastapi/security/__init__.py", line 1, in <module>
    from .api_key import APIKeyCookie as APIKeyCookie
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/fastapi/security/api_key.py", line 3, in <module>
    from fastapi.openapi.models import APIKey, APIKeyIn
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/fastapi/openapi/models.py", line 103, in <module>
    class Schema(BaseModel):
    ...<38 lines>...
            extra: str = "allow"
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/pydantic/main.py", line 286, in __new__
    cls.__try_update_forward_refs__()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/pydantic/main.py", line 807, in __try_update_forward_refs__
    update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/pydantic/typing.py", line 554, in update_model_forward_refs
    update_field_forward_refs(f, globalns=globalns, localns=localns)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/pydantic/typing.py", line 520, in update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
                  ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prithvirajuuppalapati/Library/Caches/pypoetry/virtualenvs/backend-7rcOXaf8-py3.13/lib/python3.13/site-packages/pydantic/typing.py", line 66, in evaluate_forwardref
    return cast(Any, type_)._evaluate(globalns, localns, set())
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

and upon updating openAI key, still getting error mentioned in screenshot

<img width="960" alt="image" src="https://github.com/user-attachments/assets/ceba04f1-e590-4eca-89ba-d27adda87d17">

**Comment by abi** [comment]
Can you trying rolling back to Python 3.12.3?

**Comment by prithviraju1369** [comment]
@abi Thanks

worked fine with 
python:3.12.3 & POETRY_VERSION 1.4.1 on MAC locally. Pls check latest version issue
