### ISSUE TITLE
Error generating code. Please contact support.

### ISSUE THREAD

**Issue by LiuJiaoShouYa** [abi/screenshot-to-code#416]
Incoming websocket connection...
INFO:     connection open
Received params
Using openAiApiKey from client-side settings dialog
Using official OpenAI URL
Generating html_css code in image mode using Llm.CLAUDE_3_5_SONNET_2024_06_20...
Status (variant 0): Generating code...
Status (variant 1): Generating code...
Error generating code. Please contact support.
Traceback (most recent call last):
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpcore\_async\connection.py", line 99, in handle_async_request
    raise exc
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpcore\_async\connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpcore\_async\connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpcore\_backends\auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpcore\_backends\anyio.py", line 112, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\_base_client.py", line 1470, in _request
    response = await self._client.send(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\pyfile\screenshot-to-code\backend\llm.py", line 62, in stream_openai_response
    stream = await client.chat.completions.create(**params)  # type: ignore
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\resources\chat\completions.py", line 1334, in create
    return await self._post(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\_base_client.py", line 1738, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\_base_client.py", line 1441, in request
    return await self._request(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\_base_client.py", line 1494, in _request
    return await self._retry_request(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\_base_client.py", line 1563, in _retry_request
    return await self._request(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\_base_client.py", line 1494, in _request
    return await self._retry_request(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\_base_client.py", line 1563, in _retry_request
    return await self._request(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\_base_client.py", line 1504, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
Traceback (most recent call last):
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpcore\_async\connection.py", line 99, in handle_async_request
    raise exc
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpcore\_async\connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpcore\_async\connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpcore\_backends\auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpcore\_backends\anyio.py", line 112, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\_base_client.py", line 1470, in _request
    response = await self._client.send(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\pyfile\screenshot-to-code\backend\llm.py", line 62, in stream_openai_response
    stream = await client.chat.completions.create(**params)  # type: ignore
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\resources\chat\completions.py", line 1334, in create
    return await self._post(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\_base_client.py", line 1738, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\_base_client.py", line 1441, in request
    return await self._request(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\_base_client.py", line 1494, in _request
    return await self._retry_request(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\_base_client.py", line 1563, in _retry_request
    return await self._request(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\_base_client.py", line 1494, in _request
    return await self._retry_request(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\_base_client.py", line 1563, in _retry_request
    return await self._request(
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\openai\_base_client.py", line 1504, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 250, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\starlette\middleware\cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "C:\Virtualenvs\screenshot-to-code\lib\site-packages\fastapi\routing.py", line 289, in app
    await dependant.call(**values)
  File "C:\pyfile\screenshot-to-code\backend\routes\generate_code.py", line 331, in stream_code
    raise Exception("All generations failed")
Exception: All generations failed
INFO:     connection closed

**Comment by abi** [comment]
> httpx.ConnectError: All connection attempts failed

Is the OpenAI API accessible to you?

**Comment by Harish222600** [comment]
for me also its not working and getting same error

**Comment by abi** [comment]
Impossible to debug without your logs. 

If you see a connection error, that means you don't have access to OpenAI API
