### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ulixcode-labs** [abi/screenshot-to-code#428]
@**Describe the bug**

**To Reproduce**

workstation# yarn dev 
yarn run v1.22.22
$ vite

 ERROR  error when starting dev server:                                                                                                    00:16:50
RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at /home/xw/Projects/screenshot-to-code/frontend/node_modules/dotenv-expand/lib/main.js:7:54
    at Array.reduce (<anonymous>)
    at _interpolate (/home/xw/Projects/screenshot-to-code/frontend/node_modules/dotenv-expand/lib/main.js:6:18)
    at /home/xw/Projects/screenshot-to-code/frontend/node_modules/dotenv-expand/lib/main.js:36:15
    at Array.reduce (<anonymous>)
    at _interpolate (/home/xw/Projects/screenshot-to-code/frontend/node_modules/dotenv-expand/lib/main.js:6:18)
    at /home/xw/Projects/screenshot-to-code/frontend/node_modules/dotenv-expand/lib/main.js:36:15
    at Array.reduce (<anonymous>)
    at _interpolate (/home/xw/Projects/screenshot-to-code/frontend/node_modules/dotenv-expand/lib/main.js:6:18)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Screenshots of backend AND frontend terminal logs**

**Comment by abi** [comment]
What does your .env file look like on the front-end? Please remove the exact key values but share the contents
