### ISSUE TITLE
I have to keep using VPN and need help with this problem

### ISSUE THREAD

**Issue by Shawn-Jones-7** [abi/screenshot-to-code#44]
![image](https://github.com/abi/screenshot-to-code/assets/134922845/32565fdb-d852-41f0-966f-392f7d66bfcc)
<img width="1267" alt="截屏2023-11-20 13 26 26" src="https://github.com/abi/screenshot-to-code/assets/134922845/a5f046f8-1851-4327-bfd0-fb23a0a93e29">

**Comment by Laixinsz** [comment]
Yes, I have encountered this problem too, hope it can be solved

**Comment by abi** [comment]
Please share your backend logs

**Comment by Laixinsz** [comment]
**Backend log：**
INFO:     ('127.0.0.1', 53938) - "WebSocket /generate-code" [accepted]
INFO:     connection open
Using OpenAI API key from client-side settings dialog
generating code...
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/Users/mark/Desktop/AI/screenshot-to-code-main/backend/main.py", line 100, in stream_code_test
    completion = await stream_openai_response(
  File "/Users/mark/Desktop/AI/screenshot-to-code-main/backend/llm.py", line 11, in stream_openai_response
    client = AsyncOpenAI(api_key=api_key)
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/openai/_client.py", line 313, in __init__
    super().__init__(
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/openai/_base_client.py", line 1182, in __init__
    self._client = http_client or httpx.AsyncClient(
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1408, in __init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[AsyncBaseTransport]] = {
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1411, in <dictcomp>
    else self._init_proxy_transport(
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1464, in _init_proxy_transport
    return AsyncHTTPTransport(
  File "/Users/mark/Library/Caches/pypoetry/virtualenvs/backend-LkJV4r1g-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 309, in __init__
    raise ImportError(
ImportError: Using SOCKS proxy, but the 'socksio' package is not installed. Make sure to install httpx using `pip install httpx[socks]`.
INFO:     connection closed

**Comment by Shawn-Jones-7** [comment]
INFO:     Will watch for changes in these directories: ['/Users/Data/screenshot-to-code/backend']
INFO:     Uvicorn running on http://127.0.0.1:7000 (Press CTRL+C to quit)
INFO:     Started reloader process [10044] using StatReload
INFO:     Started server process [10048]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     ('127.0.0.1', 52665) - "WebSocket /generate-code" [accepted]
INFO:     connection open
Using OpenAI API key from environment variable
generating code...
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/Users/Data/screenshot-to-code/backend/main.py", line 100, in stream_code_test
    completion = await stream_openai_response(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Data/screenshot-to-code/backend/llm.py", line 23, in stream_openai_response
    completion = await client.chat.completions.create(**params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 1191, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1474, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1275, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1318, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
INFO:     connection closed
INFO:     ('127.0.0.1', 52681) - "WebSocket /generate-code" [accepted]
INFO:     connection open
Using OpenAI API key from environment variable
generating code...
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/Users/Data/screenshot-to-code/backend/main.py", line 100, in stream_code_test
    completion = await stream_openai_response(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Data/screenshot-to-code/backend/llm.py", line 23, in stream_openai_response
    completion = await client.chat.completions.create(**params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 1191, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1474, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1275, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/Data/Library/Caches/pypoetry/virtualenvs/backend-7PreVEuP-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1318, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
INFO:     connection closed

**Comment by abi** [comment]
@Shawn-Jones-7 your API key doesn't have the vision model available. Please see FAQ. " {'error': {'message': 'The model gpt-4-vision-preview does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}"

@Laixinsz can you try running `pip install httpx[socks]` as your logs suggest?

**Comment by abi** [comment]
Going to close this issue. Feel free to re-open if those fixes don't solve it.

**Comment by liberalisman** [comment]
I have encountered this problem too and I have installed httpx[socks],but same problem
