### ISSUE TITLE
"WebSocketDisconnect (<CloseCode.ABNORMAL_CLOSURE: 1006>, None)"

### ISSUE THREAD

**Issue by ChutchawanGit** [abi/screenshot-to-code#442]
Could the WebSocket closure with error code 1006 be related to the video recording feature used for generating web pages? 

INFO:     connection open
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 250, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\starlette\middleware\errors.py", line 152, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\starlette\middleware\cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\starlette\routing.py", line 362, in handle
    await self.app(scope, receive, send)
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\starlette\routing.py", line 95, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\starlette\routing.py", line 93, in app
    await func(session)
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\fastapi\routing.py", line 383, in app
    await dependant.call(**solved_result.values)
  File "C:\Users\chutchawan.m\screenshot-to-code\backend\routes\generate_code.py", line 206, in stream_code
    params: dict[str, str] = await websocket.receive_json()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\starlette\websockets.py", line 135, in receive_json
    self._raise_on_disconnect(message)
  File "C:\Users\chutchawan.m\AppData\Local\pypoetry\Cache\virtualenvs\backend-K2HrQqBb-py3.12\Lib\site-packages\starlette\websockets.py", line 113, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"], message.get("reason"))
starlette.websockets.WebSocketDisconnect: (<CloseCode.ABNORMAL_CLOSURE: 1006>, None)
INFO:     connection closed

**Comment by abi** [comment]
Yes. Does it work for images for you?
