### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by kdodoo** [abi/screenshot-to-code#443]
When running the frontend yarn dev command, I get the error below.

1. Go to frontend folder
2. execute: `yarn`
3. execute: `yarn dev`

Immediately after executing the yarn dev command, I get a message that says:
```
 ERROR                                                                                                                           16:31:02
[TypeScript] Found 0 errors. Watching for file changes.
```

Then when I navigate to http://localhost:5173/, it crashes with the following output:

```
(base) user@192 frontend % yarn dev        
yarn run v1.22.22
warning ../../../package.json: No license field
$ vite
                                                                                                                                 16:31:00
  VITE v4.5.0  ready in 544 ms

  ➜  Local:   http://localhost:5173/                                                                                             16:31:00
  ➜  Network: use --host to expose                                                                                               16:31:00
  ➜  press h to show help                                                                                                        16:31:00

 ERROR                                                                                                                           16:31:02
[TypeScript] Found 0 errors. Watching for file changes.


 WARN  Browserslist: caniuse-lite is outdated. Please run:                                                                       16:31:37
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme


 ERROR  (node:91140) ExperimentalWarning: CommonJS module /Users/user/Desktop/screenshot-to-code/frontend/node_modules/tailwindcss/lib/lib/load-config.js is loading ES Module /Users/user/Desktop/screenshot-to-code/frontend/tailwind.config.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

file:///Users/user/Desktop/screenshot-to-code/frontend/tailwind.config.js:2
module.exports = {
^

ReferenceError: module is not defined
    at file:///Users/user/Desktop/screenshot-to-code/frontend/tailwind.config.js:2:1
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:395:35)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:329:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1376:24)
    at Module._compile (node:internal/modules/cjs/loader:1528:5)
    at Object..js (node:internal/modules/cjs/loader:1698:10)
    at Module.load (node:internal/modules/cjs/loader:1303:32)
    at Function._load (node:internal/modules/cjs/loader:1117:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1325:12)
    at require (node:internal/modules/helpers:136:16)
    at /Users/user/Desktop/screenshot-to-code/frontend/node_modules/tailwindcss/lib/lib/load-config.js:35:27
    at loadConfig (/Users/user/Desktop/screenshot-to-code/frontend/node_modules/tailwindcss/lib/lib/load-config.js:39:6)
    at getTailwindConfig (/Users/user/Desktop/screenshot-to-code/frontend/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:71:116)
    at /Users/user/Desktop/screenshot-to-code/frontend/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:100:92
    at /Users/user/Desktop/screenshot-to-code/frontend/node_modules/tailwindcss/lib/processTailwindFeatures.js:48:11
    at plugins (/Users/user/Desktop/screenshot-to-code/frontend/node_modules/tailwindcss/lib/plugin.js:38:69)
    at LazyResult.runOnRoot (/Users/user/Desktop/screenshot-to-code/frontend/node_modules/postcss/lib/lazy-result.js:329:16)
    at LazyResult.runAsync (/Users/user/Desktop/screenshot-to-code/frontend/node_modules/postcss/lib/lazy-result.js:258:26)
    at LazyResult.async (/Users/user/Desktop/screenshot-to-code/frontend/node_modules/postcss/lib/lazy-result.js:160:30)
    at LazyResult.then (/Users/user/Desktop/screenshot-to-code/frontend/node_modules/postcss/lib/lazy-result.js:404:17)

Node.js v23.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by abi** [comment]
You can safely ignore the first "ERROR"

The module is not defined error is often due to some yarn/node configuration on your end. It's a really annoying error that I sometimes get (with other projects) but I can never remember what the fix is.

Claude suggests this but I'm not sure if it will fix your problem.

<img width="709" alt="Screenshot 2024-11-28 at 11 54 19 AM" src="https://github.com/user-attachments/assets/70840b87-2407-4d4a-a35c-f37da23c6dae">

**Comment by kdodoo** [comment]
Renaming to .cjs worked! You think it should be defaulted to it or is it going to break other platforms?

**Comment by abi** [comment]
Awesome, I'll wait to hear more complaints before updating it.

**Comment by ShiBody** [comment]
Renaming to .cjs works for me as well. Changing to "export default" still got errors on my device.
