### ISSUE TITLE
Error while generating

### ISSUE THREAD

**Issue by JuanjoRC8** [abi/screenshot-to-code#450]
When generating from any image got error.
![error](https://github.com/user-attachments/assets/0112b26d-7a88-496a-9c26-ec3ba40193ba)

Got this in the console log:
![image](https://github.com/user-attachments/assets/53350e10-8934-42fc-b763-e24d2df954b3)
And this in the backend:
![image](https://github.com/user-attachments/assets/46430016-3c83-4d48-87c3-d30929296743)
![image](https://github.com/user-attachments/assets/c1e80ad4-c934-4785-916d-d360bc8b501c)

**Comment by abi** [comment]
Try https://github.com/abi/screenshot-to-code/issues/386#issuecomment-2276756980

**Comment by SimpleDioney** [comment]
PS C:\Users\dione\Downloads\screenshot-to-code-main\screenshot-to-code-main\backend> python --version
Python 3.12.3
PS C:\Users\dione\Downloads\screenshot-to-code-main\screenshot-to-code-main\backend> poetry run uvicorn main:app --reload --port 7001
INFO:     Will watch for changes in these directories: ['C:\\Users\\dione\\Downloads\\screenshot-to-code-main\\screenshot-to-code-main\\backend']
INFO:     Uvicorn running on http://127.0.0.1:7001 (Press CTRL+C to quit)
INFO:     Started reloader process [31888] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\uvicorn\config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\dione\Downloads\screenshot-to-code-main\screenshot-to-code-main\backend\main.py", line 4, in <module>
    load_dotenv()
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\dotenv\main.py", line 356, in load_dotenv
    return dotenv.set_as_environment_variables()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\dotenv\main.py", line 92, in set_as_environment_variables
    if not self.dict():
           ^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\dotenv\main.py", line 76, in dict
    self._dict = OrderedDict(resolve_variables(raw_values, override=self.override))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\dotenv\main.py", line 238, in resolve_variables
    for (name, value) in values:
                         ^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\dotenv\main.py", line 84, in parse
    for mapping in with_warn_for_invalid_lines(parse_stream(stream)):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\dotenv\main.py", line 26, in with_warn_for_invalid_lines
    for mapping in mappings:
                   ^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\dotenv\parser.py", line 173, in parse_stream
    reader = Reader(stream)
             ^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\dotenv\parser.py", line 64, in __init__
    self.string = stream.read()
                  ^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by abi** [comment]
Please see the README for a solution to this problem.

**Comment by SimpleDioney** [comment]
I ran the step by step and it continues:

File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\fastapi\routing.py", line 24, in <module>
(backend-py3.12) PS C:\Users\dione\Downloads\screenshot-to-code-main\screenshot-to-code-main\backend\backend> poetry run uvicorn main:app --reload --port 7000
INFO:     Will watch for changes in these directories: ['C:\\Users\\dione\\Downloads\\screenshot-to-code-main\\screenshot-to-code-main\\backend\\backend']
INFO:     Uvicorn running on http://127.0.0.1:7000 (Press CTRL+C to quit)
INFO:     Started reloader process [12992] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\uvicorn\config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\dione\Downloads\screenshot-to-code-main\screenshot-to-code-main\backend\backend\main.py", line 7, in <module>
    from fastapi import FastAPI
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\fastapi\applications.py", line 16, in <module>
    from fastapi import routing
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\fastapi\routing.py", line 24, in <module>
    from fastapi.dependencies.models import Dependant
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\fastapi\dependencies\models.py", line 3, in <module>
    from fastapi.security.base import SecurityBase
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\fastapi\security\__init__.py", line 1, in <module>
    from .api_key import APIKeyCookie as APIKeyCookie
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\fastapi\security\api_key.py", line 3, in <module>
    from fastapi.openapi.models import APIKey, APIKeyIn
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\fastapi\openapi\models.py", line 103, in <module>
    class Schema(BaseModel):
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\pydantic\main.py", line 286, in __new__
    cls.__try_update_forward_refs__()
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\pydantic\main.py", line 807, in __try_update_forward_refs__
    update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\pydantic\typing.py", line 554, in update_model_forward_refs
    update_field_forward_refs(f, globalns=globalns, localns=localns)
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\pydantic\typing.py", line 520, in update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\pydantic\typing.py", line 66, in evaluate_forwardref
    return cast(Any, type_)._evaluate(globalns, localns, set())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

**Comment by abi** [comment]
This error should be fixed by https://github.com/abi/screenshot-to-code/issues/386#issuecomment-2276756980

**Comment by SimpleDioney** [comment]
(backend-py3.12) PS C:\Users\dione\Downloads\screenshot-to-code-main\screenshot-to-code-main\backend\backend> poetry run uvicorn main:app --reload --port 7001
INFO:     Will watch for changes in these directories: ['C:\\Users\\dione\\Downloads\\screenshot-to-code-main\\screenshot-to-code-main\\backend\\backend']
INFO:     Uvicorn running on http://127.0.0.1:7001 (Press CTRL+C to quit)
INFO:     Started reloader process [20084] using StatReload
C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\moviepy\config_defaults.py:1: SyntaxWarning: invalid escape sequence '\P'
  """
C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\moviepy\video\io\ffmpeg_reader.py:294: SyntaxWarning: invalid escape sequence '\d'
  lines_video = [l for l in lines if ' Video: ' in l and re.search('\d+x\d+', l)]
C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\moviepy\video\io\ffmpeg_reader.py:367: SyntaxWarning: invalid escape sequence '\d'
  rotation_lines = [l for l in lines if 'rotate          :' in l and re.search('\d+$', l)]
C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\moviepy\video\io\ffmpeg_reader.py:370: SyntaxWarning: invalid escape sequence '\d'
  match = re.search('\d+$', rotation_line)
INFO:     Started server process [8232]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     ('127.0.0.1', 49719) - "WebSocket /generate-code" [accepted]
Incoming websocket connection...
INFO:     connection open
Received params
Using anthropicApiKey from client-side settings dialog
Using official OpenAI URL
Generating html_tailwind code in image mode
Status (variant 0): Generating code...
Status (variant 1): Generating code...
[CLAUDE IMAGE PROCESSING] no processing needed
[CLAUDE IMAGE PROCESSING] no processing needed
Error generating code. Please contact support.
Traceback (most recent call last):
  File "C:\Users\dione\Downloads\screenshot-to-code-main\screenshot-to-code-main\backend\backend\llm.py", line 128, in stream_claude_response
    async with client.messages.stream(
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\anthropic\lib\streaming\_messages.py", line 305, in __aenter__
    raw_stream = await self.__api_request
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\anthropic\_base_client.py", line 1838, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\anthropic\_base_client.py", line 1532, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\anthropic\_base_client.py", line 1633, in _request
    raise self._make_status_error_from_response(err.response) from None
anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'Your credit balance is too low to access the Anthropic API. Please go to Plans & Billing to upgrade or purchase credits.'}}
Traceback (most recent call last):
  File "C:\Users\dione\Downloads\screenshot-to-code-main\screenshot-to-code-main\backend\backend\llm.py", line 128, in stream_claude_response
    async with client.messages.stream(
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\anthropic\lib\streaming\_messages.py", line 305, in __aenter__
    raw_stream = await self.__api_request
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\anthropic\_base_client.py", line 1838, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\anthropic\_base_client.py", line 1532, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\anthropic\_base_client.py", line 1633, in _request
    raise self._make_status_error_from_response(err.response) from None
anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'Your credit balance is too low to access the Anthropic API. Please go to Plans & Billing to upgrade or purchase credits.'}}
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 250, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\starlette\middleware\cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "C:\Users\dione\AppData\Local\pypoetry\Cache\virtualenvs\backend-ChyaHEbJ-py3.12\Lib\site-packages\fastapi\routing.py", line 289, in app
    await dependant.call(**values)
  File "C:\Users\dione\Downloads\screenshot-to-code-main\screenshot-to-code-main\backend\routes\generate_code.py", line 336, in stream_code
    raise Exception("All generations failed")
Exception: All generations failed
INFO:     connection closed

**Comment by JuanjoRC8** [comment]
I did downgrade with pyenv to python 3.12.2 and again got the same issue, but this time this is the log: 
![image](https://github.com/user-attachments/assets/fca74bdd-1457-405b-b48c-206aedde0664)
![image](https://github.com/user-attachments/assets/5ab59bef-2fbc-4e4a-94b7-ff43d1cfeb1d)
Here in plain text:
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\uvicorn\config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Juanjo\Documents\Github\screenshot-to-code\backend\main.py", line 7, in <module>
    from fastapi import FastAPI
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\fastapi\applications.py", line 16, in <module>
    from fastapi import routing
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\fastapi\routing.py", line 24, in <module>
    from fastapi.dependencies.models import Dependant
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\fastapi\dependencies\models.py", line 3, in <module>
    from fastapi.security.base import SecurityBase
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\fastapi\security\__init__.py", line 1, in <module>
    from .api_key import APIKeyCookie as APIKeyCookie
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\fastapi\security\api_key.py", line 3, in <module>
    from fastapi.openapi.models import APIKey, APIKeyIn
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\fastapi\openapi\models.py", line 103, in <module>
    class Schema(BaseModel):
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\pydantic\main.py", line 286, in __new__
    cls.__try_update_forward_refs__()
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\pydantic\main.py", line 807, in __try_update_forward_refs__
    update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\pydantic\typing.py", line 554, in update_model_forward_refs
    update_field_forward_refs(f, globalns=globalns, localns=localns)
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\pydantic\typing.py", line 520, in update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Juanjo\AppData\Local\pypoetry\Cache\virtualenvs\backend-0aiVKvt6-py3.12\Lib\site-packages\pydantic\typing.py", line 66, in evaluate_forwardref
    return cast(Any, type_)._evaluate(globalns, localns, set())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
