### ISSUE TITLE
Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue.

### ISSUE THREAD

**Issue by artemmarkov050** [abi/screenshot-to-code#464]
![2024-12-23_16-02-04](https://github.com/user-attachments/assets/c17dc8bb-43ef-4fdb-a4dd-94450f2f806d)

there is such a problem, has anyone encountered it? How to solve it?

**Comment by yeboahd24** [comment]
Not interested again.

**Comment by abi** [comment]
@artemmarkov050 please share your backend and front-end logs to help with debugging.

**Comment by TuanVnit** [comment]
I am facing a similar issue as the one mentioned above. I have made a domain public for everyone to use based on the LAN IP. People access the link I shared with the IP, and then the mentioned error appears.
![image](https://github.com/user-attachments/assets/72194651-472c-4ad1-a923-d39f3ed2ba7c)

**Comment by abi** [comment]
@TuanVnit yes you need to update the backend URL env if you're accessing it from a front-end on a different computer.

**Comment by ericlarslee** [comment]
This is the primary error I get on the backend:
PS C:\Users\ericl\Downloads\screenshot-to-code-main\screenshot-to-code-main\backend> poetry run uvicorn main:app --reload --port 7001
INFO:     Will watch for changes in these directories: ['C:\\Users\\ericl\\Downloads\\screenshot-to-code-main\\screenshot-to-code-main\\backend']
INFO:     Uvicorn running on http://127.0.0.1:7001 (Press CTRL+C to quit)
INFO:     Started reloader process [2164] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Python313\Lib\multiprocessing\process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "C:\Python313\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ericl\AppData\Local\pypoetry\Cache\virtualenvs\backend-ulQFLN8h-py3.13\Lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ericl\AppData\Local\pypoetry\Cache\virtualenvs\backend-ulQFLN8h-py3.13\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Python313\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\ericl\AppData\Local\pypoetry\Cache\virtualenvs\backend-ulQFLN8h-py3.13\Lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
    ~~~~~~~~~~~^^
  File "C:\Users\ericl\AppData\Local\pypoetry\Cache\virtualenvs\backend-ulQFLN8h-py3.13\Lib\site-packages\uvicorn\config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ericl\AppData\Local\pypoetry\Cache\virtualenvs\backend-ulQFLN8h-py3.13\Lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\ericl\Downloads\screenshot-to-code-main\screenshot-to-code-main\backend\main.py", line 4, in <module>
    load_dotenv()
    ~~~~~~~~~~~^^
  File "C:\Users\ericl\AppData\Local\pypoetry\Cache\virtualenvs\backend-ulQFLN8h-py3.13\Lib\site-packages\dotenv\main.py", line 356, in load_dotenv
    return dotenv.set_as_environment_variables()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ericl\AppData\Local\pypoetry\Cache\virtualenvs\backend-ulQFLN8h-py3.13\Lib\site-packages\dotenv\main.py", line 92, in set_as_environment_variables
    if not self.dict():
           ~~~~~~~~~^^
  File "C:\Users\ericl\AppData\Local\pypoetry\Cache\virtualenvs\backend-ulQFLN8h-py3.13\Lib\site-packages\dotenv\main.py", line 76, in dict
    self._dict = OrderedDict(resolve_variables(raw_values, override=self.override))
                             ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ericl\AppData\Local\pypoetry\Cache\virtualenvs\backend-ulQFLN8h-py3.13\Lib\site-packages\dotenv\main.py", line 238, in resolve_variables
    for (name, value) in values:
                         ^^^^^^
  File "C:\Users\ericl\AppData\Local\pypoetry\Cache\virtualenvs\backend-ulQFLN8h-py3.13\Lib\site-packages\dotenv\main.py", line 84, in parse
    for mapping in with_warn_for_invalid_lines(parse_stream(stream)):
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ericl\AppData\Local\pypoetry\Cache\virtualenvs\backend-ulQFLN8h-py3.13\Lib\site-packages\dotenv\main.py", line 26, in with_warn_for_invalid_lines
    for mapping in mappings:
                   ^^^^^^^^
  File "C:\Users\ericl\AppData\Local\pypoetry\Cache\virtualenvs\backend-ulQFLN8h-py3.13\Lib\site-packages\dotenv\parser.py", line 173, in parse_stream
    reader = Reader(stream)
  File "C:\Users\ericl\AppData\Local\pypoetry\Cache\virtualenvs\backend-ulQFLN8h-py3.13\Lib\site-packages\dotenv\parser.py", line 64, in __init__
    self.string = stream.read()
                  ~~~~~~~~~~~^^
  File "<frozen codecs>", line 325, in decode

**Comment by abi** [comment]
@ericlarslee i think something is up with your .env file. I think there's a utf-8 fix described in the README

**Comment by onewhowritesCP** [comment]
I am getting the same error. I dont see any error in the backend, it is generating code successfully, but still getting this error sometimes. Also, I am using GPT 4.1 mini model. Application gets stuck sometimes and streaming is not happening. Any help?
