### ISSUE TITLE
Error generating code. Please contact support.

### ISSUE THREAD

**Issue by Fox-Me** [abi/screenshot-to-code#466]
The docker image and containers are loading, after fixing some js to cjs file rename, however, I receive below error when uploading printscreen, video or code. I'm using Ollama, locally, with Llava and following variables:

screenshot-to-code\backend .env
OPENAI_BASE_URL=http://localhost:11434/v1
OPENAI_API_KEY=fake-key

screenshot-to-code\frontend .env
OPENAI_BASE_URL=http://localhost:11434/v1
OPENAI_API_KEY=fake-key

No Frontend error, but:

Page Error: Error generating code. Please contact support.

Backend Errors:

2024-12-24 15:53:33 INFO:     ('172.18.0.1', 53064) - "WebSocket /generate-code" [accepted]
2024-12-24 15:53:33 INFO:     connection open
2024-12-24 15:53:34 Traceback (most recent call last):
2024-12-24 15:53:34   File "/app/llm.py", line 128, in stream_claude_response
2024-12-24 15:53:34     async with client.messages.stream(
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/anthropic/lib/streaming/_messages.py", line 305, in __aenter__
2024-12-24 15:53:34     raw_stream = await self.__api_request
2024-12-24 15:53:34                  ^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/anthropic/_base_client.py", line 1838, in post
2024-12-24 15:53:34     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
2024-12-24 15:53:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/anthropic/_base_client.py", line 1532, in request
2024-12-24 15:53:34     return await self._request(
2024-12-24 15:53:34            ^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/anthropic/_base_client.py", line 1633, in _request
2024-12-24 15:53:34     raise self._make_status_error_from_response(err.response) from None
2024-12-24 15:53:34 anthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}}
2024-12-24 15:53:34 Traceback (most recent call last):
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
2024-12-24 15:53:34     yield
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
2024-12-24 15:53:34     resp = await self._pool.handle_async_request(req)
2024-12-24 15:53:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request
2024-12-24 15:53:34     raise exc from None
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
2024-12-24 15:53:34     response = await connection.handle_async_request(
2024-12-24 15:53:34                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
2024-12-24 15:53:34     raise exc
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 78, in handle_async_request
2024-12-24 15:53:34     stream = await self._connect(request)
2024-12-24 15:53:34              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 124, in _connect
2024-12-24 15:53:34     stream = await self._network_backend.connect_tcp(**kwargs)
2024-12-24 15:53:34              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
2024-12-24 15:53:34     return await self._backend.connect_tcp(
2024-12-24 15:53:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 113, in connect_tcp
2024-12-24 15:53:34     with map_exceptions(exc_map):
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
2024-12-24 15:53:34     self.gen.throw(value)
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2024-12-24 15:53:34     raise to_exc(exc) from exc
2024-12-24 15:53:34 httpcore.ConnectError: All connection attempts failed
2024-12-24 15:53:34 
2024-12-24 15:53:34 The above exception was the direct cause of the following exception:
2024-12-24 15:53:34 
2024-12-24 15:53:34 Traceback (most recent call last):
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1576, in _request
2024-12-24 15:53:34     response = await self._client.send(
2024-12-24 15:53:34                ^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1617, in send
2024-12-24 15:53:34     response = await self._send_handling_auth(
2024-12-24 15:53:34                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
2024-12-24 15:53:34     response = await self._send_handling_redirects(
2024-12-24 15:53:34                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
2024-12-24 15:53:34     response = await self._send_single_request(request)
2024-12-24 15:53:34                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1719, in _send_single_request
2024-12-24 15:53:34     response = await transport.handle_async_request(request)
2024-12-24 15:53:34                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 365, in handle_async_request
2024-12-24 15:53:34     with map_httpcore_exceptions():
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
2024-12-24 15:53:34     self.gen.throw(value)
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
2024-12-24 15:53:34     raise mapped_exc(message) from exc
2024-12-24 15:53:34 httpx.ConnectError: All connection attempts failed
2024-12-24 15:53:34 
2024-12-24 15:53:34 The above exception was the direct cause of the following exception:
2024-12-24 15:53:34 
2024-12-24 15:53:34 Traceback (most recent call last):
2024-12-24 15:53:34   File "/app/llm.py", line 62, in stream_openai_response
2024-12-24 15:53:34     stream = await client.chat.completions.create(**params)  # type: ignore
2024-12-24 15:53:34              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 1720, in create
2024-12-24 15:53:34     return await self._post(
2024-12-24 15:53:34            ^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1843, in post
2024-12-24 15:53:34     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
2024-12-24 15:53:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1537, in request
2024-12-24 15:53:34     return await self._request(
2024-12-24 15:53:34            ^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1600, in _request
2024-12-24 15:53:34     return await self._retry_request(
2024-12-24 15:53:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1670, in _retry_request
2024-12-24 15:53:34     return await self._request(
2024-12-24 15:53:34            ^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1600, in _request
2024-12-24 15:53:34     return await self._retry_request(
2024-12-24 15:53:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1670, in _retry_request
2024-12-24 15:53:34     return await self._request(
2024-12-24 15:53:34            ^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1610, in _request
2024-12-24 15:53:34     raise APIConnectionError(request=request) from err
2024-12-24 15:53:34 openai.APIConnectionError: Connection error.
2024-12-24 15:53:34 ERROR:    Exception in ASGI application
2024-12-24 15:53:34 Traceback (most recent call last):
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 250, in run_asgi
2024-12-24 15:53:34     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
2024-12-24 15:53:34              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-12-24 15:53:34     return await self.app(scope, receive, send)
2024-12-24 15:53:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
2024-12-24 15:53:34     await super().__call__(scope, receive, send)
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
2024-12-24 15:53:34     await self.middleware_stack(scope, receive, send)
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 152, in __call__
2024-12-24 15:53:34     await self.app(scope, receive, send)
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 77, in __call__
2024-12-24 15:53:34     await self.app(scope, receive, send)
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-12-24 15:53:34     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-12-24 15:53:34     raise exc
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2024-12-24 15:53:34     await app(scope, receive, sender)
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
2024-12-24 15:53:34     await self.middleware_stack(scope, receive, send)
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
2024-12-24 15:53:34     await route.handle(scope, receive, send)
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 362, in handle
2024-12-24 15:53:34     await self.app(scope, receive, send)
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 95, in app
2024-12-24 15:53:34     await wrap_app_handling_exceptions(app, session)(scope, receive, send)
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-12-24 15:53:34     raise exc
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2024-12-24 15:53:34     await app(scope, receive, sender)
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 93, in app
2024-12-24 15:53:34     await func(session)
2024-12-24 15:53:34   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 383, in app
2024-12-24 15:53:34     await dependant.call(**solved_result.values)
2024-12-24 15:53:34   File "/app/routes/generate_code.py", line 335, in stream_code
2024-12-24 15:53:34     raise Exception("All generations failed")
2024-12-24 15:53:34 Exception: All generations failed
2024-12-24 15:53:34 INFO:     connection closed

**Comment by abi** [comment]
The issue is in the logs: 

 anthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}}
