### ISSUE TITLE
Error generating code. Please contact support.

### ISSUE THREAD

**Issue by pagnkelly** [abi/screenshot-to-code#467]
Error generating code. Please contact support.
Traceback (most recent call last):
  File "/Users/didi/code/github.com/abi/screenshot-to-code/backend/llm.py", line 40, in stream_openai_response
    client = AsyncOpenAI(api_key=api_key, base_url=base_url)
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/openai/_client.py", line 357, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        version=__version__,
        ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        _strict_response_validation=_strict_response_validation,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/openai/_base_client.py", line 1443, in __init__
    self._client = http_client or AsyncHttpxClientWrapper(
                                  ~~~~~~~~~~~~~~~~~~~~~~~^
        base_url=base_url,
        ^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        **kwargs,  # type: ignore
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/openai/_base_client.py", line 1337, in __init__
    super().__init__(**kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/httpx/_client.py", line 1411, in __init__
    else self._init_proxy_transport(
         ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        proxy,
        ^^^^^^
    ...<5 lines>...
        trust_env=trust_env,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/httpx/_client.py", line 1464, in _init_proxy_transport
    return AsyncHTTPTransport(
        verify=verify,
    ...<4 lines>...
        proxy=proxy,
    )
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/httpx/_transports/default.py", line 309, in __init__
    raise ImportError(
    ...<2 lines>...
    ) from None
ImportError: Using SOCKS proxy, but the 'socksio' package is not installed. Make sure to install httpx using `pip install httpx[socks]`.
Traceback (most recent call last):
  File "/Users/didi/code/github.com/abi/screenshot-to-code/backend/llm.py", line 40, in stream_openai_response
    client = AsyncOpenAI(api_key=api_key, base_url=base_url)
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/openai/_client.py", line 357, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        version=__version__,
        ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        _strict_response_validation=_strict_response_validation,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/openai/_base_client.py", line 1443, in __init__
    self._client = http_client or AsyncHttpxClientWrapper(
                                  ~~~~~~~~~~~~~~~~~~~~~~~^
        base_url=base_url,
        ^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        **kwargs,  # type: ignore
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/openai/_base_client.py", line 1337, in __init__
    super().__init__(**kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/httpx/_client.py", line 1411, in __init__
    else self._init_proxy_transport(
         ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        proxy,
        ^^^^^^
    ...<5 lines>...
        trust_env=trust_env,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/httpx/_client.py", line 1464, in _init_proxy_transport
    return AsyncHTTPTransport(
        verify=verify,
    ...<4 lines>...
        proxy=proxy,
    )
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/httpx/_transports/default.py", line 309, in __init__
    raise ImportError(
    ...<2 lines>...
    ) from None
ImportError: Using SOCKS proxy, but the 'socksio' package is not installed. Make sure to install httpx using `pip install httpx[socks]`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 250, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/starlette/middleware/errors.py", line 152, in __call__
    await self.app(scope, receive, send)
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/starlette/middleware/cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 362, in handle
    await self.app(scope, receive, send)
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 95, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/starlette/routing.py", line 93, in app
    await func(session)
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/fastapi/routing.py", line 383, in app
    await dependant.call(**solved_result.values)
  File "/Users/didi/code/github.com/abi/screenshot-to-code/backend/routes/generate_code.py", line 335, in stream_code
    raise Exception("All generations failed")
Exception: All generations failed
INFO:     connection closed
Task exception was never retrieved
future: <Task finished name='Task-11' coro=<AsyncClient.aclose() done, defined at /Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/httpx/_client.py:1967> exception=AttributeError("'AsyncHttpxClientWrapper' object has no attribute '_mounts'")>
Traceback (most recent call last):
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/httpx/_client.py", line 1975, in aclose
    for proxy in self._mounts.values():
                 ^^^^^^^^^^^^
AttributeError: 'AsyncHttpxClientWrapper' object has no attribute '_mounts'
Task exception was never retrieved
future: <Task finished name='Task-12' coro=<AsyncClient.aclose() done, defined at /Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/httpx/_client.py:1967> exception=AttributeError("'AsyncHttpxClientWrapper' object has no attribute '_mounts'")>
Traceback (most recent call last):
  File "/Users/didi/Library/Caches/pypoetry/virtualenvs/backend-3aP43wfi-py3.13/lib/python3.13/site-packages/httpx/_client.py", line 1975, in aclose
    for proxy in self._mounts.values():
                 ^^^^^^^^^^^^
AttributeError: 'AsyncHttpxClientWrapper' object has no attribute '_mounts'

**Comment by abi** [comment]
Have you tried ImportError: Using SOCKS proxy, but the 'socksio' package is not installed. Make sure to install httpx using pip install httpx[socks].
