### ISSUE TITLE
Error generating code. Check the Developer Console for details. Feel free to open a Github issue

### ISSUE THREAD

**Issue by tanphat2k4** [abi/screenshot-to-code#67]
I can't generate code. please help me..!
![Screenshot 2023-11-21 at 5 29 59 PM](https://github.com/abi/screenshot-to-code/assets/31386840/d2e093c3-ac23-4ac1-a69b-6605f1a1a2f1)

**Comment by yujingr** [comment]
same for me. The code exists but isn't functional, missing parts and incorrect syntax here and there, which is probably why the previews doesn't render.

**Comment by hkcitizens9527** [comment]
me too

**Comment by Adarsh7825** [comment]
@abi could you just provide us more detail about this issue

It would be helpful

**Comment by abi** [comment]
Going to need your backend logs to debug this. If you look at the backend logs, check the FAQ section to see if the fixes there solve it.

**Comment by 2424004764** [comment]
me too

**Comment by augustus2389** [comment]
@tanphat2k4 đã fix được chưa hả ông?

**Comment by tanphat2k4** [comment]
> @tanphat2k4 đã fix được chưa hả ông?

chưa bạn ơi :)

**Comment by DaveySwift** [comment]
same error for me. Even when using your hosted version. Nothing is created. 

Cool app and concept.

![error](https://github.com/abi/screenshot-to-code/assets/20891671/94b77148-65f2-4b68-8ad0-3a752827f6ae)

**Comment by nicolastilly** [comment]
same here. I dot this https://github.com/abi/screenshot-to-code/issues/3#issuecomment-1814777959 but doesn't works :/

<img width="900" alt="Capture d’écran 2023-11-22 à 11 20 51" src="https://github.com/abi/screenshot-to-code/assets/1997136/66286436-804e-4713-bd89-9d95a67b340e">

**Comment by abi** [comment]
Hi yall please post your backend logs so we can debug. Without that there's no information to know why code generation failed.

**Comment by nicolastilly** [comment]
> Hi yall please post your backend logs so we can debug. Without that there's no information to know why code generation failed.

it finally works. I've redone the installation and the code is now properly generated.

**Comment by alexgarciab** [comment]
same error here

![Screenshot 2023-11-22 at 13 28 25](https://github.com/abi/screenshot-to-code/assets/6924386/d4755c89-17dd-4df2-ab5a-e442ee19b0e9)

**Comment by Adarsh7825** [comment]
@abi  backend logs 

 2023-11-21 16:51:58 screenshot-to-code-backend-1   |     await func(session)
2023-11-21 16:51:58 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 289, in app
2023-11-21 16:51:58 screenshot-to-code-backend-1   |     await dependant.call(**values)
2023-11-21 16:51:58 screenshot-to-code-backend-1   |   File "/app/main.py", line 117, in stream_code_test
2023-11-21 16:51:58 screenshot-to-code-backend-1   |     completion = await stream_openai_response(
2023-11-21 16:51:58 screenshot-to-code-backend-1   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21 16:51:58 screenshot-to-code-backend-1   |   File "/app/llm.py", line 23, in stream_openai_response
2023-11-21 16:51:58 screenshot-to-code-backend-1   |     completion = await client.chat.completions.create(**params)
2023-11-21 16:51:58 screenshot-to-code-backend-1   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21 16:51:58 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 1191, in create
2023-11-21 16:51:58 screenshot-to-code-backend-1   |     return await self._post(
2023-11-21 16:51:58 screenshot-to-code-backend-1   |            ^^^^^^^^^^^^^^^^^
2023-11-21 16:51:58 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1474, in post
2023-11-21 16:51:58 screenshot-to-code-backend-1   |     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
2023-11-21 16:51:58 screenshot-to-code-backend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21 16:51:58 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1275, in request
2023-11-21 16:51:58 screenshot-to-code-backend-1   |     return await self._request(
2023-11-21 16:51:58 screenshot-to-code-backend-1   |            ^^^^^^^^^^^^^^^^^^^^
2023-11-21 16:51:58 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1318, in _request
2023-11-21 16:51:58 screenshot-to-code-backend-1   |     raise self._make_status_error_from_response(err.response) from None
2023-11-21 16:51:58 screenshot-to-code-backend-1   | openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2023-11-21 16:51:58 screenshot-to-code-backend-1   | INFO:     connection closed
2023-11-21 23:05:02 screenshot-to-code-backend-1   | INFO:     Shutting down
2023-11-21 23:05:02 screenshot-to-code-backend-1   | INFO:     Waiting for application shutdown.
2023-11-21 23:05:02 screenshot-to-code-backend-1   | INFO:     Application shutdown complete.
2023-11-21 23:05:02 screenshot-to-code-backend-1   | INFO:     Finished server process [1]
2023-11-21 23:05:02 screenshot-to-code-backend-1   | Using OpenAI API key from client-side settings dialog
2023-11-21 23:05:02 screenshot-to-code-backend-1   | generating code...
2023-11-21 23:05:13 screenshot-to-code-backend-1   | Skipping virtualenv creation, as specified in config file.
2023-11-21 23:05:14 screenshot-to-code-backend-1   | INFO:     Started server process [1]
2023-11-21 23:05:14 screenshot-to-code-backend-1   | INFO:     Waiting for application startup.
2023-11-21 23:05:14 screenshot-to-code-backend-1   | INFO:     Application startup complete.
2023-11-21 23:05:14 screenshot-to-code-backend-1   | INFO:     Uvicorn running on http://0.0.0.0:7001 (Press CTRL+C to quit)
2023-11-21 23:06:25 screenshot-to-code-backend-1   | INFO:     ('172.19.0.1', 34098) - "WebSocket /generate-code" [accepted]
2023-11-21 23:06:25 screenshot-to-code-backend-1   | INFO:     connection open
2023-11-21 23:06:32 screenshot-to-code-backend-1   | ERROR:    Exception in ASGI application
2023-11-21 23:06:32 screenshot-to-code-backend-1   | Traceback (most recent call last):
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
2023-11-21 23:06:32 screenshot-to-code-backend-1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     return await self.app(scope, receive, send)
2023-11-21 23:06:32 screenshot-to-code-backend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 276, in __call__
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     await super().__call__(scope, receive, send)
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 122, in __call__
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     await self.middleware_stack(scope, receive, send)
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 149, in __call__
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     await self.app(scope, receive, send)
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 75, in __call__
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     await self.app(scope, receive, send)
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     raise exc
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     await self.app(scope, receive, sender)
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     raise e
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     await self.app(scope, receive, send)
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 718, in __call__
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     await route.handle(scope, receive, send)
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 341, in handle
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     await self.app(scope, receive, send)
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 82, in app
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     await func(session)
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 289, in app
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     await dependant.call(**values)
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/app/main.py", line 117, in stream_code_test
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     completion = await stream_openai_response(
2023-11-21 23:06:32 screenshot-to-code-backend-1   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/app/llm.py", line 23, in stream_openai_response
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     completion = await client.chat.completions.create(**params)
2023-11-21 23:06:32 screenshot-to-code-backend-1   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 1191, in create
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     return await self._post(
2023-11-21 23:06:32 screenshot-to-code-backend-1   |            ^^^^^^^^^^^^^^^^^
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1474, in post
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
2023-11-21 23:06:32 screenshot-to-code-backend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1275, in request
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     return await self._request(
2023-11-21 23:06:32 screenshot-to-code-backend-1   |            ^^^^^^^^^^^^^^^^^^^^
2023-11-21 23:06:32 screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1318, in _request
2023-11-21 23:06:32 screenshot-to-code-backend-1   |     raise self._make_status_error_from_response(err.response) from None
2023-11-21 23:06:32 screenshot-to-code-backend-1   | openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2023-11-21 23:06:32 screenshot-to-code-backend-1   | INFO:     connection closed

**Comment by Adarsh7825** [comment]
@abi do i need to use Gpt 4 api ?

**Comment by abi** [comment]
@Adarsh7825 yes: {'error': {'message': 'The model gpt-4-vision-preview does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

See https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4

**Comment by tanphat2k4** [comment]
> > Hi yall please post your backend logs so we can debug. Without that there's no information to know why code generation failed.
> 
> it finally works. I've redone the installation and the code is now properly generated.

hi @nicolastilly , I have a question : you are using chatGPT4.0.?
