### ISSUE TITLE
Rate limit reached for gpt-4-vision-preview in organization xxxxx 

### ISSUE THREAD

**Issue by MrFiregore** [abi/screenshot-to-code#76]
With only single request i give this error:

```
screenshot-to-code-backend-1   | INFO:     ('172.20.0.1', 49694) - "WebSocket /generate-code" [accepted]
screenshot-to-code-backend-1   | INFO:     connection open
screenshot-to-code-backend-1   | ERROR:    Exception in ASGI application
screenshot-to-code-backend-1   | Traceback (most recent call last):
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
screenshot-to-code-backend-1   |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
screenshot-to-code-backend-1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
screenshot-to-code-backend-1   |     return await self.app(scope, receive, send)
screenshot-to-code-backend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 276, in __call__
screenshot-to-code-backend-1   |     await super().__call__(scope, receive, send)
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 122, in __call__
screenshot-to-code-backend-1   |     await self.middleware_stack(scope, receive, send)
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 149, in __call__
screenshot-to-code-backend-1   |     await self.app(scope, receive, send)
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 75, in __call__
screenshot-to-code-backend-1   |     await self.app(scope, receive, send)
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
screenshot-to-code-backend-1   |     raise exc
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
screenshot-to-code-backend-1   |     await self.app(scope, receive, sender)
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
screenshot-to-code-backend-1   |     raise e
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
screenshot-to-code-backend-1   |     await self.app(scope, receive, send)
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 718, in __call__
screenshot-to-code-backend-1   |     await route.handle(scope, receive, send)
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 341, in handle
screenshot-to-code-backend-1   |     await self.app(scope, receive, send)
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 82, in app
screenshot-to-code-backend-1   |     await func(session)
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 289, in app
screenshot-to-code-backend-1   |     await dependant.call(**values)
screenshot-to-code-backend-1   |   File "/app/main.py", line 117, in stream_code
screenshot-to-code-backend-1   |     completion = await stream_openai_response(
screenshot-to-code-backend-1   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
screenshot-to-code-backend-1   |   File "/app/llm.py", line 23, in stream_openai_response
screenshot-to-code-backend-1   |     completion = await client.chat.completions.create(**params)
screenshot-to-code-backend-1   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 1191, in create
screenshot-to-code-backend-1   |     return await self._post(
screenshot-to-code-backend-1   |            ^^^^^^^^^^^^^^^^^
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1474, in post
screenshot-to-code-backend-1   |     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
screenshot-to-code-backend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1275, in request
screenshot-to-code-backend-1   |     return await self._request(
screenshot-to-code-backend-1   |            ^^^^^^^^^^^^^^^^^^^^
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1306, in _request
screenshot-to-code-backend-1   |     return await self._retry_request(
screenshot-to-code-backend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1356, in _retry_request
screenshot-to-code-backend-1   |     return await self._request(
screenshot-to-code-backend-1   |            ^^^^^^^^^^^^^^^^^^^^
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1306, in _request
screenshot-to-code-backend-1   |     return await self._retry_request(
screenshot-to-code-backend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1356, in _retry_request
screenshot-to-code-backend-1   |     return await self._request(
screenshot-to-code-backend-1   |            ^^^^^^^^^^^^^^^^^^^^
screenshot-to-code-backend-1   |   File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1318, in _request
screenshot-to-code-backend-1   |     raise self._make_status_error_from_response(err.response) from None
screenshot-to-code-backend-1   | openai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4-vision-preview in organization xxxxxxxx on tokens per min (TPM): Limit 10000, Used 6701, Requested 4497. Please try again in 7.188s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
screenshot-to-code-backend-1   | INFO:     connection closed
```

**Comment by abi** [comment]
Looks like there's a token limit. See the last line: tokens per min (TPM): Limit 10000, Used 6701, Requested 4497. Please try again in 7.188s.

If you tried again, did it work?
